### ISSUE TITLE
 The entities show and hide frequently

### ISSUE THREAD

**Issue by SettingDust** [Meldexun/EntityCulling#1]
**Describe the bug**
Entities are blinking when enable
skipHiddenEntityRendering

**To Reproduce**
1. Watching them
2. Far away

**Versions**
Entity Culling:EntityCulling-1.0.2.jar
Forge:1.12.2 2854
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
That is not enough information.
A video of your problem would probably be helpful because like I said I haven't experienced what you are saying.
And please make sure that this bug happens with only Entity Culling installed and otherwise list the other mods necessary to reproduce the bug.

**Comment by Meldexun** [comment]
Fixed in v1.0.3
