### ISSUE TITLE
[Question] Config variable meanings?

### ISSUE THREAD

**Issue by MrKashew** [Meldexun/EntityCulling#11]
Silly question: what does `skipHiddenEntityRenderingSize`, and `skipHiddenEntityRenderingDiff` refer to in config? Are these distance values for culling to occur

**Comment by Meldexun** [comment]
skipHiddenEntityRenderingSize
Entities with a width or height greater than this value will always get rendered.

skipHiddenEntityRenderingDiff
It raytraces from the eyes of the player to the eyes of the entity and the other way around. Then it compares the positions that were hit and only renders the entity when no block was hit or the distance between both points is lower than this setting.
