### ISSUE TITLE
Crash upon start up

### ISSUE THREAD

**Issue by Pi0nStEaM** [Meldexun/EntityCulling#12]
A flat out crash on my private modpack only when I introduce EntityCulling to it.
(It crashes on start up ... no crash file is created because of this

The crash is practically impossible to reproduce for yourself.  Considering that the modpack I added EnitityCulling to is my own private pack.

**Versions**
Entity Culling: 1.12.2-4.0.0
Forge: 14.23.5.2847
Minecraft: 1.12.2

**Other**
I was playing on Singleplayer.
As far as mods go I have 180.  I wish I could find an exact mod list from my pack.

Should the issue not be from "EntityCulling" and there is nothing you can do about it ... or the issue probably came from one of the180 other mods, then just let me know.
(There are a TON of things(Errors/bugs) going on in my pack that I have not gotten around to fix yet.)

[latest.log](https://github.com/Meldexun/EntityCulling/files/6120330/latest.log)

**Comment by Meldexun** [comment]
*Copied from the curseforge page*
`Entity Culling - 1.12.2 - 2.0.8 and newer versions are only compatible with Optifine G5!`

**Comment by Pi0nStEaM** [comment]
> 
> 
> _Copied from the curseforge page_
> `Entity Culling - 1.12.2 - 2.0.8 and newer versions are only compatible with Optifine G5!`

Ah, I could have sworn I was using that version.  I'll check again.
