### ISSUE TITLE
entities and water render through everything

### ISSUE THREAD

**Issue by releaseHUN** [Meldexun/EntityCulling#14]
with forge version 36.1.0 and 36.1.1 the entities and water and some leaves render through solid blocks, you can see the water underground and every mob behind blocks. i first found the issue with optifine(HD_U_G7) installed, but even after removing optifine the issue persisted.

![image](https://user-images.githubusercontent.com/24492359/111884204-5653f100-89c0-11eb-8a70-3eaf2fe7010e.png)
![image](https://user-images.githubusercontent.com/24492359/111884220-797ea080-89c0-11eb-9e9b-f0e6b10d8e9a.png)

you can reproduce the issue by simply playing
entity culling was version 2.0.6

**Comment by Meldexun** [comment]
I'm unable to reproduce this with forge 36.1.0 and entity culling 2.0.6

**Comment by Meldexun** [comment]
Can be reopened when it is reproducible with just Entity Culling (and less than 5 other mods) installed.
