### ISSUE TITLE
Probably my error

### ISSUE THREAD

**Issue by ComputerJock** [Meldexun/EntityCulling#16]
Came here via Xisuma's reference. 

From the description it sort of sounded like Optifine was optional. I tried the mod with Fabric and it was not loaded because it's not a Fabric mod. My error.

Is there any chance you might be supporting a Fabric version?

**Comment by Meldexun** [comment]
No, but there is a similar mod which works on fabric:
https://www.curseforge.com/minecraft/mc-mods/entityculling
