### ISSUE TITLE
Rendering crash?

### ISSUE THREAD

**Issue by border999** [Meldexun/EntityCulling#17]
**Describe the bug**
Tried to spark a nether portal to correct for it changing where it lets out in the nether. When I attempted to open the nether portal side back to the overworld it opened properly and rendered the other side but crashed a few moments later. (Using Better Portals.

**Expected behavior**
Not crashing.

**Versions**
Entity Culling: EntityCulling-1.12.2-4.0.5
Better Portals: BetterPortals-0.3.7.7
Optifine: OptiFine_1.12.2_HD_U_G5
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report (upload as a file):
[crash-2021-03-25_06.28.13-client.txt](https://github.com/Meldexun/EntityCulling/files/6206403/crash-2021-03-25_06.28.13-client.txt)

Latest log (upload as a file): [latest.log](https://github.com/Meldexun/EntityCulling/files/6206416/latest.log)
Singleplayer

**Comment by Meldexun** [comment]
Might be fixed in v1.12.2-4.1.2
Though keep in mind EntityCulling most likely won't work correctly with mods like Better Portals
