### ISSUE TITLE
Failed to start Minecraft (on 2.11)

### ISSUE THREAD

**Issue by marc-cwm** [Meldexun/EntityCulling#19]
**Describe the bug**
Error does not mention Entity Culling that I can see, but if Entity Culling is present, the newest version seems to fail on startup.  If we remove Entity Culling or revert to 2.0.6 , we load as expected.

**To Reproduce**
Crash early on in startup process.  Normally, the next step after the crash would be from FastBench and some more items from AstralSorcery.

**Versions**
Entity Culling: 1.16.5-2.11
Forge: 36.0.42
Minecraft: 1.16.5

Errored log with modlist on 2.11:
https://paste.ee/p/DQChj

Working log with modlist on  2.06:
https://paste.ee/p/D8bd3

**Comment by moisties** [comment]
having this issue too. it seems when i remove either Entity Culling or Architectury minecraft starts fine, but with these two mods in the mods folder at the same time it doesn't launch completely before crashing.

**Comment by Meldexun** [comment]
Should be fixed in v1.16.5-2.1.2

Though the new version only fixes a bug when optifine is installed. So when it is still crashing without optifine please create another issue.

**Comment by marc-cwm** [comment]
Confirmed, new version works fine with Optifine installed now.
