### ISSUE TITLE
[Issue] Render issue with Sync

### ISSUE THREAD

**Issue by gatoborrachon** [Meldexun/EntityCulling#2]
**Describe the bug**
The chambers from Sync mod are badly rendered, the glass is the only thing rendered.

**To Reproduce**
1. Install Sync and Entity Culling 
2. Place any Sync chamber
3. See error

**Expected behavior**
you will see how it is badly rendered

**Screenshots**
Without EntityCulling
![2020-12-15_13 21 10](https://user-images.githubusercontent.com/61126174/102269373-250be680-3ee2-11eb-8197-242958ff3946.png)

With Entity Culling 2.0.0
![2020-12-15_14 27 01](https://user-images.githubusercontent.com/61126174/102269390-2b9a5e00-3ee2-11eb-8af7-9bfe8cdd974b.png)

**Versions**
Entity Culling: 2.0.0
Forge: 14.23.5.2854
Minecraft: 1.12.2
Sync: 7.1.0

**Other**
Latest log (upload as a file):
[2020-12-15-4.log](https://github.com/Meldexun/EntityCulling/files/5698459/2020-12-15-4.log)

Singleplayer
Other mods (Sync):

**Comment by Meldexun** [comment]
I'm unable to reproduce the issue with only entity culling and sync. Please check what mods are needed to reproduce the issue.

**Comment by gatoborrachon** [comment]
you can see the issue? or you mean that you will look into the log and see which mods i have? i have like 200+ so if you want i can do a binary search

**Comment by Meldexun** [comment]
I can reproduce the issue with only entity culling and sync

**Comment by gatoborrachon** [comment]
ok

**Comment by Meldexun** [comment]
It's an issue on their end. I will open an issue on their side but I don't think there will be an update.

**Comment by gatoborrachon** [comment]
yeah, Ichun will never fix it, anyways thanks, i will keep using 1.0.3

**Comment by gatoborrachon** [comment]
mmm, is there a way to blacklist tile entities?

**Comment by Meldexun** [comment]
Entity Culling changes the way minecraft iterates over the render chunks and checks wether or not to render an entity/tile entity. That means there can't be a blacklist because the vanilla code is never called.
(the blacklist in the config is there to blacklist entities from the skipHiddenTileEntityRendering feature)

**Comment by gatoborrachon** [comment]
oh, ok. 
well, the last thing i can say, you know how to fix this inside Sync? i don't know much about coding, but at least i can build a dev environment with the mod, the issue here is that i have no idea what to change, and how do it, but you know which changes do? i know everything has a license, but i will just it for personal use

**Comment by Meldexun** [comment]
Wanted to tell you about that right now.
It should be enough to change 1 file:
Sync/src/main/java/me/ichun/mods/sync/client/render/TileRendererDualVertical.java

In there just replace every `BlockDualVertical.renderPass` with `MinecraftForgeClient.getRenderPass()`
And add `import net.minecraftforge.client.MinecraftForgeClient;` to the imports at the top of the file.

**Comment by gatoborrachon** [comment]
many many thanks, really, i will try it right now and report it to you.

**Comment by gatoborrachon** [comment]
sorry for taking much, yeah it worked, i'm going to open a pull request, just for formality

**Comment by leonpano2006** [comment]
> sorry for taking much, yeah it worked, i'm going to open a pull request, just for formality

can you make own release cause by Ichun 99% chance not going to merge it or close anything
you are safe to do that as longest you fellow GNU GPLv3(should be easy)
