### ISSUE TITLE
(1.12.2) Body from Naga boss from The Twilight Forest doesn't render

### ISSUE THREAD

**Issue by SpecialtyK** [Meldexun/EntityCulling#21]
**Describe the bug**
Only the head and not the body segments render when this mod is enabled. Adding "twilightforest:twilightforest.naga" or "twilightforest:twilightforest_naga" and many other variations to the blacklist do not seem to affect rendering of this entity. Disabling this mod entirely allows me to see all of the Naga again. Perhaps I am not inputting the correct blacklist or another mod conflict?

**To Reproduce**
1. Enable entity culling mod and The Twilight Forest mod
2. Spawn Naga boss
3. See error

**Expected behavior**
I expect to be able to blacklist the Naga from the entity culling mod and be able to see all the segments of the body

**Screenshots**

![2021-04-25_20 35 09](https://user-images.githubusercontent.com/83197538/116026007-a0a34000-a606-11eb-80ee-92b99bcceb22.png)
![2021-04-25_20 25 24](https://user-images.githubusercontent.com/83197538/116026015-a731b780-a606-11eb-8f0a-c61a9acbf162.png)
![2021-04-25_20 35 43](https://user-images.githubusercontent.com/83197538/116026028-ae58c580-a606-11eb-94d7-d009324b903b.png)

**Versions**
Entity Culling: 4.1.2
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report (upload as a file):
Latest log (upload as a file): [Log.txt](https://github.com/Meldexun/EntityCulling/files/6374180/Log.txt)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): 
 [📁] 1.12 (folder)
  [✔️] AbyssalCraft+Integration-1.12.2-1.11.2
  [✔️] AbyssalCraft-1.12.2-1.10.3
  [✔️] Aether Continuation v1.3.0
  [✔️] aether-1.12.2-v1.5.3.1
  [✔️] AIImprovements-1.12-0.0.1b3
  [✔️] AIReducer-1.12.2-0.2.1
  [✔️] AkashicTome-1.2-12
  [✔️] ancientspellcraft-1.1.3
  [✔️] animania-1.12.2-base-2.0.3.28
  [✔️] animania-1.12.2-extra-1.0.2.28
  [✔️] animania-1.12.2-farm-1.0.2.28
  [✔️] Apotheosis-1.12.2-1.12.5
  [✔️] AppleCore-mc1.12.2-3.4.0
  [✔️] AppleSkin-mc1.12-1.0.14
  [✔️] AquaCreepers-1.2.3
  [✔️] Aquaculture-1.12.2-1.6.8
  [✔️] ArtemisLib-1.12.2-v1.0.6
  [✔️] Atum-1.12.2-2.0.20
  [✔️] AutoRegLib-1.3-32
  [✔️] BattleTowers-1.12.2
  [✔️] Baubles-1.12-1.5.2
  [✔️] BetterAdvancements-1.12.2-0.1.0.77
  [✔️] betteranimals-1.12.2-5.5.0
  [✔️] betteranimalsplus-1.12.2-9.0.1
  [✔️] bettercaves-1.12.2-2.0.4
  [✔️] BetterDiving-1.12.2-1.5.8
  [✔️] BetterFps-1.4.8
  [✔️] BetterMineshaftsForge-1.12.2-2.2.1
  [✔️] BetterPlacement-1.0.0-1
  [✔️] BiblioCraft[v2.4.5][MC1.12.2]
  [✔️] biggerpacketsplz-since1.8-1.2
  [✔️] Biome_Bundle-1.12.2-v6.1
  [✔️] bonsaitrees-1.1.4-b170
  [✔️] Bookshelf-1.12.2-2.3.590
  [✔️] Bountiful+Baubles-1.12.2-0.1.6
  [✔️] Bountiful-2.2.2
  [✔️] BuildingGadgets-2.8.4
  [✔️] callablehorses-1.12.2-1.1
  [✔️] Cavern_1.12.2-v2.3.1
  [✔️] Chameleon-1.12-4.1.3
  [✔️] ChanceCubes-1.12.2-5.0.2.385
  [✔️] Charm-1.12.2-1.4.1
  [✔️] ChestTransporter-1.12.2-2.8.8
  [✔️] ChickenChunks-1.12.2-2.4.2.74-universal
  [✔️] Chisel-MC1.12.2-1.0.2.45
  [✔️] Chocolate_Quest_Repoured-1.12.2-2.5.2B
  [✔️] ChunkAnimator-MC1.12-1.2
  [✔️] Clumps-3.1.2
  [✔️] CodeChickenLib-1.12.2-3.2.3.358-universal
  [✔️] ColossalChests-1.12.2-1.7.3
  [✔️] comforts-1.12.2-1.4.1.3
  [✔️] Controlling-3.0.10
  [✔️] CookingForBlockheads_1.12.2-6.5.0
  [✔️] CoralReef-2.5-1.12.2
  [✔️] coroutil-1.12.1-1.2.37
  [✔️] CosmeticArmorReworked-1.12.2-v5a
  [✔️] CraftingTweaks_1.12.2-8.1.9
  [✔️] CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha
  [✔️] CraftTweaker2-1.12-4.1.20.625
  [✔️] creeperconfetti-1.4.2
  [✔️] crimsonrevelations-0.8
  [✔️] CTM-MC1.12.2-1.0.2.31
  [✔️] Cucumber-1.12.2-1.1.3
  [✔️] Customized-Dungeon-Loot-1.12 -(v.1.0.3)
  [✔️] CustomMainMenu-MC1.12.2-2.0.9.1
  [✔️] Cyclic-1.12.2-1.20.6
  [✔️] CyclopsCore-1.12.2-1.6.7
  [✔️] DankNull-1.12.2-1.7.101
  [✔️] DefaultSettings-1.8.x-1.12.x-2.2.0
  [✔️] DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL
  [✔️] disenchanter[1.12]1.7
  [✔️] DoggyTalents-1.12.2-1.15.1.6
  [✔️] DoomlikeDungeons-1.13.2-MC1.12.2
  [✔️] DungeonTactics-1.12.2-0.16.9
  [✔️] DynamicSurroundings-1.12.2-3.6.0.2
  [✔️] easiervillagertrading-1.12-forge14.21.1.2387-1.3
  [✔️] EerieEntities-1.12.2-1.0.7
  [✔️] ElectroblobsWizardry-4.3.4-MC1.12.2
  [✔️] elenaidodge-1.12.2-1.13.2
  [✔️] Embersified-1.12.2-1.0.3
  [✔️] EmbersRekindled-1.18
  [✔️] EnchantmentDescriptions-1.12.2-1.1.15
  [✔️] EndReborn+[0.3.9]
  [✔️] EngineersWorkshopReborn-1.12.2-1.0.9.40
  [✔️] EntityCulling-1.12.2-4.1.2
  [✔️] Erebus-1.0.32
  [✔️] extraalchemy-forge-1.12-build11-0.5.4
  [✔️] ExtraGolems-1.12-7.1.9
  [✔️] ExtraSpells-1.12.2-1.2.0
  [✔️] extrautils2-1.12-1.9.9
  [✔️] eyeofdragons-0.0.2
  [✔️] FastWorkbench-1.12.2-1.7.3
  [✔️] Fish's+Undead+Rising-1.2.3
  [✔️] foamfix-0.10.10-1.12.2
  [✔️] FoodExpansion1.3.3-1.12.2
  [✔️] forge-1.12.2-geckolib-3.0.0-beta.7
  [✔️] ForgeEndertech-1.12.2-4.5.5.0-build.0561
  [✔️] Forgelin-1.8.4
  [✔️] fossilsarcheology-8.0.5
  [✔️] FTBBackups-1.1.0.1
  [✔️] FTBGuides-2.0.0.52
  [✔️] FTBLib-5.4.7.2
  [✔️] FTBQuests-1202.9.0.15
  [✔️] FTBUtilities-5.4.1.131
  [✔️] future-mc-1.12.2-0.2.6.1
  [✔️] gogredux-1.12.2-1.0.0
  [✔️] GrimoireOfGaia3-1.12.2-1.7.2
  [✔️] harvestersnight-1.12.2-1.1.0
  [📁] hats (folder)
  [✔️] Hats-1.12.2-7.1.1
  [✔️] HatStand-1.12.2-7.1.0
  [✔️] heroicarmory-1.2.0
  [✔️] hooked-1.0.3
  [✔️] hostileworlds_invasions-1.12.1-1.1.13
  [✔️] Hwyla-1.8.26-B41_1.12.2
  [✔️] iceandfire-1.9.1-1.12.2
  [✔️] iChunUtil-1.12.2-7.2.2
  [✔️] ImprovedBackpacks-1.12.2-1.5.0.0
  [✔️] InfernalMobs-1.12.2
  [✔️] inventorypets-1.12-2.0.12
  [✔️] InventoryTweaks-1.63
  [✔️] ItemFilters-1.0.4.2
  [✔️] ItemPhysic Lite 1.3.7 mc1.12.2
  [✔️] IvToolkit-1.3.3-1.12
  [✔️] jei_1.12.2-4.16.1.302
  [✔️] jeiintegration_1.12.2-1.6.0
  [✔️] JJ+Meteor+1.12-1.12.2-v1.0.10
  [✔️] journeymap-1.12.2-5.7.1
  [✔️] just-enough-harvestcraft-1.12.2-1.7.2
  [✔️] JustEnoughIDs-1.0.3-48
  [✔️] landsoficaria-beta-1.12.2-1.0.1-hotfix
  [✔️] letsencryptcraft-1.10.2-1.2.0
  [✔️] levelup2-1.2.3
  [✔️] librarianlib-1.12.2-4.22
  [✔️] LibraryEx-1.12.2-1.2.1
  [✔️] limelib-1.12.2-1.7.12
  [✔️] living_enchantment-3.2.3
  [✔️] llibrary-1.7.20-1.12.2
  [✔️] LoadingProfiler-MC1.12-1.3
  [✔️] Login_Shield-1.12.2-6-g5654706
  [✔️] loliasm-1.1
  [✔️] lost-aether-content-1.12.2-1.0.2
  [✔️] LostBooks-II-1.12.2-2.0.3
  [✔️] LunatriusCore-1.12.2-1.2.0.42-universal
  [✔️] MagmaMonsters-0.3.0
  [✔️] MainMenuScale-1.3.2
  [✔️] MCA-1.12.2-6.1.0-universal
  [✔️] megaloot-1.12.2-0.2.40
  [📁] memory_repo (folder)
  [✔️] mia-1.12.2-0.2.0e
  [✔️] minecolonies-1.12.2-0.11.841-ALPHA-universal
  [✔️] MineMenu-1.12.2-1.6.11-universal
  [✔️] minerva-library-1.0.13
  [✔️] MobController-1.12.2-1.1
  [✔️] moreoverlays-1.15.1-mc1.12.2
  [✔️] MoreSwordsLegacy-1.12.2-1.0.7
  [✔️] MouseTweaks-2.10-mc1.12.2
  [✔️] mowziesmobs-1.5.8
  [✔️] MultiMine-1.12.2
  [✔️] MutantBeasts-1.12.2-1.0.2
  [✔️] Mystical Mechanics-0.18
  [✔️] MysticalAgriculture-1.12.2-1.7.5
  [✔️] mysticallib-1.12.2-1.10.0
  [✔️] mysticalworld-1.12.2-1.9.4
  [✔️] NaturesCompass-1.12.2-1.8.5
  [✔️] Neat 1.4-17
  [✔️] NetherEx-1.12.2-2.2.4
  [✔️] NetherPortalFix_1.12.1-5.3.17
  [✔️] NomadicTents-1.12.2-9.5.2
  [✔️] NoMoreRecipeConflict-0.13(1.12.2)
  [✔️] noRecipeBook_v1.2.2formc1.12.2
  [✔️] Nyx-1.4.2
  [✔️] OpenBlocks-1.12.2-1.8.1
  [✔️] OpenModsLib-1.12.2-0.12.2
  [📁] OpenTerrainGenerator (folder)
  [✔️] OpenTerrainGenerator-1.12.2-v9.3
  [✔️] OreLib-1.12.2-3.6.0.1
  [✔️] p455w0rdslib-1.12.2-2.3.161
  [✔️] Pam's HarvestCraft 1.12.2zg
  [✔️] Patchouli-1.0-23.6
  [✔️] phosphor-1.12.2-0.2.6+build50-universal
  [✔️] PiTweaks-1.12-1.1.1
  [✔️] placeableitems-3.3
  [✔️] Placebo-1.12.2-1.6.0
  [✔️] PortableCrafting-1.12.2-1.0.2
  [✔️] PotionCore-1.9_for_1.12.2
  [✔️] prefab-1.3.0.26
  [✔️] ProgressiveBosses-1.5.4-mc1.12.x
  [✔️] ProjectVibrantJourneys-1.12.2-1.6.4
  [✔️] PyramidPlunder-1.12.2-1.4
  [✔️] QualityTools-1.0.7_for_1.12.2
  [✔️] QuarkOddities-1.12.2
  [✔️] Quark-r1.6-179
  [✔️] Quest-Revamped-04-12-2021
  [✔️] randomloot 1.7.4
  [✔️] randompatches-1.12.2-1.22.1.10
  [✔️] RandomThings-MC1.12.2-4.2.7.4
  [✔️] randomtweaks-1.12.2-2.8.2.2
  [✔️] reauth-3.6.0
  [✔️] RebornCore-1.12.2-3.19.4.529-universal
  [✔️] RecurrentComplex-1.4.8.2
  [✔️] Reliquary-1.12.2-1.3.4.796
  [✔️] ResourceLoader-MC1.12.1-1.5.3
  [✔️] Rex's-Additional-Structures-1.12.x-(v.2.3.1)
  [✔️] RoguelikeDungeonsFnarEdition-1.12.2-2.3.1
  [✔️] ropebridge-1.12-2.0.7
  [✔️] roughTweaks0.2.4-1.12.2
  [✔️] Ruins-1.12.2
  [✔️] rustic-1.1.7
  [✔️] ScalingHealth-1.12.2-1.3.42+147
  [✔️] sharetome-1.0
  [✔️] signpost-1.12.2-1.08.5
  [✔️] SilentLib-1.12.2-3.0.14+168
  [✔️] SimpleStorageNetwork-1.12.2-1.8.0
  [✔️] Skewers-1.1
  [✔️] skylanterns-1.12.1-1.0.1
  [✔️] SmoothEntityLight-4.0.4-MC1.12.2
  [✔️] SnowRealMagic-0.3.3
  [✔️] solcarrot-1.12.2-1.8.4
  [✔️] Soot-1.10-hotfix
  [✔️] SoundFilters-0.12.1_for_1.12
  [✔️] spartanfire-0.08
  [✔️] SpartanShields-1.12.2-1.5.4
  [✔️] SpartanWeaponry-1.12.2-beta-1.3.8
  [✔️] SpawnerControl-1.6.3b
  [✔️] SpawnTemple-v.2.1-mc1.12
  [✔️] specialmobs-1.0.2_for_mc1.12.2
  [✔️] SRParasites-1.12.2v1.8.2
  [✔️] Stackie-1.12.2-1.6.0.48-universal
  [✔️] stg-1.12.2-1.2.3
  [✔️] StorageDrawers-1.12.2-5.4.2
  [✔️] strawgolem-1.4.1
  [✔️] StuffASockInIt-1.12.2-1.1.30
  [✔️] SubSwitch1.1.0
  [✔️] Surge-1.12.2-2.0.77
  [✔️] terracartreloaded-1.12.2-1.2.3
  [✔️] TexFix+V-1.12-4.0
  [✔️] TFSpellPack-1.1.0-MC1.12.2
  [✔️] Thaumcraft-1.12.2-6.1.BETA26
  [✔️] ThaumicAugmentation-1.12.2-2.0.13
  [✔️] ThaumicInventoryScanning_1.12.2-2.0.10
  [✔️] ThaumicJEI-1.12.2-1.6.0-27
  [✔️] thaumicspeedup-2.0
  [✔️] The Beneath-1.12.2-1.7.0
  [✔️] theaurorian-1.12.2-release-mar2321
  [✔️] TheBetweenlands-3.7.3-universal
  [✔️] Tips-1.12.2-1.0.9
  [✔️] titlechanger-1.1.4
  [✔️] Titles-1.12.2-3.1.7
  [✔️] tombstone-4.1.2-1.12.2
  [✔️] Trinkets+and+Baubles-0.30.1
  [✔️] tumbleweed-1.12-0.4.7
  [✔️] twilightforest-1.12.2-3.11.1021-universal
  [✔️] Unique Enchantments-1.12.2-1.9.0
  [✔️] uniquecrops-1.12.2-0.2.5
  [✔️] universalbestiary-1.12.2-1.3.1
  [✔️] unloader-1.2.0
  [✔️] Uppers-0.0.6
  [✔️] VanillaFix-1.0.10-99
  [✔️] VanillaTweaks-1.12.2-1.5.6
  [✔️] ViesCraft-1.12.2-5.9.16
  [✔️] VTweaks-1.12.2-2.0.8
  [✔️] WailaHarvestability-mc1.12-1.1.12
  [✔️] Wawla-1.12.2-2.6.275
  [✔️] Waystones_1.12.2-4.1.0
  [✔️] weather2-1.12.1-2.6.12
  [✔️] WizardryGolems-1.0.1
  [✔️] world_generation_profiler-[1.8-1.12.2]-1.2.1.5
  [✔️] Worlds+Retold-+(v1.0.7)+14.23.5.2784
  [✔️] xptome-1.12.2-v2.0
  [✔️] yoyos_1.12.2-1.3.3.25

**Comment by Meldexun** [comment]
The registry name of the naga is `twilightforest:naga`

**Comment by SpecialtyK** [comment]
I tried twilightforest:naga and several variations of it as well and none seem to work. I even disabled all other mods except Twilight Forest and Entity culling, spawned new nagas, and left the game and came back and nothing seems to work. For some reason the blacklist isn't working for the Naga on my end.

**Comment by SpecialtyK** [comment]
I can confirm that it is working now. Thank you for the update.
