### ISSUE TITLE
Entity culling 1.0 for 1.16.4+ seems compatible with G6

### ISSUE THREAD

**Issue by gglobensky** [Meldexun/EntityCulling#22]
If I try to load Minecraft with Optifine G6 and Entity Culling 1.0, everything seems to work fine.

G6 always seemed faster IMO and that's the opinion of the people I test my modpack with too.

Do you think Entity Culling is actually working or just ignored? We seen an improvement but it might be a placebo effect.

**Comment by Meldexun** [comment]
I don't understand what you issue is. But you will only receive support for the newest version of mods.
