### ISSUE TITLE
Horrible Mixin Crash on 1.16.5 modpack loading.

### ISSUE THREAD

**Issue by Kaleidio** [Meldexun/EntityCulling#23]
**Describe the bug**
Three mods are known to be accessing the camera transformer (of class WorldRenderer) to do their graphical calculations in my pack.  Crayfish's Gun Mod, Physics mod, and Entity Culling.  If I remove entity culling everything works fine, but the moment I add it, there is a mixin conflict that causes forge to close before even saying anything about it in the logs.

**To Reproduce**
Download Kaleidio's Battle Pack from curseforge.
Install Entity Culling into it.
Install Optifine G8 pre12.
Launch and crash.

**Expected behavior**
Well uh...just don't crash?  This seems like an advanced mixin conflict bug...

**Screenshots**
N/A

**Versions**
Entity Culling: 2.1.3
Forge: 36.1.13
Minecraft: 1.16.5

**Other**
Crash report (upload as a file):
Latest log (upload as a file):
[latest.log](https://github.com/Meldexun/EntityCulling/files/6409808/latest.log)
Singleplayer/Multiplayer:
Other mods (that are necessary to produce the bug): *seemingly) Physics Mod, Optifine G8 pre 12 and Crayfish's Gun Mod.
Other mods (that are also installed): Kaleidio's Battle Pack.

**Comment by Meldexun** [comment]
optifine preview versions are not supported.

**Comment by Kaleidio** [comment]
Magic.  G7 is functional.

I shall test further and post any bugs I find as I am attempting to re-import Entity Culling after I had terrible lag issues with it last month.

**Comment by Kaleidio** [comment]
wait, wrong instance.  god how am I half asleep

**Comment by Kaleidio** [comment]
aye, G7 works, never mind.  sorry for the trouble

**Comment by Kaleidio** [comment]
oh my god how stupid am I, I forgot to install it...

**Comment by Kaleidio** [comment]
aight yeah, G7 is fine...
