### ISSUE TITLE
Game crash when loading world

### ISSUE THREAD

**Issue by Lupus590** [Meldexun/EntityCulling#26]
**Describe the bug**
MC crashes when loading singleplayer world

**To Reproduce**
1. load a pre existing world after updating the mod

**Expected behavior**
world loads with no issues

**Versions**
Entity Culling: 2.1.5
Forge: 36.1.0
Minecraft: 1.16.5

**Other**
Crash report (upload as a file): https://gist.github.com/Lupus590/007a198766578933a981ef8471b1574a
Latest log (upload as a file):
Singleplayer/Multiplayer: singleplayer
Other mods (that are necessary to produce the bug):
Other mods (that are also installed): there's a list in the log

**Comment by Meldexun** [comment]
Please test which mod is incompatible or if the bug also happens without any other mods installed.

**Comment by Meldexun** [comment]
Fixed in v1.16.5-2.1.6
