### ISSUE TITLE
(1.12.2) Water appearing in boats IS BACK

### ISSUE THREAD

**Issue by PlanetSun3** [Meldexun/EntityCulling#27]
Issue 10, which this clones, was briefly fixed in versions 2.0.9 and 3.0.1, but water appearing in boats is back in version 4 and above of Entity Culling.

1. Go into a world
2. Summon a boat
3. Notice how the water in the boat is back

**Expected behavior**
No water in the boat.

**Screenshots**
![2021-05-28_13 23 13](https://user-images.githubusercontent.com/61162198/120026817-40fad480-bfb8-11eb-9792-a4c78ab19401.png)

**Versions**
Entity Culling: 4.0.0+ (tested with 4.1.4)
Forge: 2855
Minecraft: 1.12.2

**Other**
Singleplayer/Multiplayer: Both
Other mods (that are necessary to produce the bug): None
Other mods (that are also installed): None

**Comment by Meldexun** [comment]
Fixed in v1.12.2-4.1.5
