### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mxnmnm** [Meldexun/EntityCulling#28]
**Describe the bug**
crash

**To Reproduce**
I randomly crashed

**Expected behavior**
no crash

**Versions**
Entity Culling:
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report (upload as a file):
[crash-2021-05-29_18.45.56-client.txt](https://github.com/Meldexun/EntityCulling/files/6565555/crash-2021-05-29_18.45.56-client.txt)
[crash-2021-05-29_18.45.58-server.txt](https://github.com/Meldexun/EntityCulling/files/6565556/crash-2021-05-29_18.45.58-server.txt)

Latest log (upload as a file): 
[2021-05-29-3.log](https://github.com/Meldexun/EntityCulling/files/6565557/2021-05-29-3.log)

Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): No clue
Other mods (that are also installed): Way too many to list (the crash report should have a list)

**Comment by Kaleidio** [comment]
you're gonna have to research for us more on which mod is conflicting, as I personally use this version without crashes.  Sounds to me like a mod has entity rendering code of some kind that is jank.

**Comment by gatoborrachon** [comment]
@mxnmnm is it a modpack?

i really would recommend to do a binary search (take half of your mods and try to reproduce the issue)

it may take a while, but if you don't provide the exact conflicting mod, i think that Meldexun will not do anything

**Comment by mxnmnm** [comment]
Yea I didn't run into this issue enough to where I'm going to bother doing this. I can't even remember what situation it happened. If it does happen enough to where it becomes an issue I will look into it, but I have better uses of my time.
