### ISSUE TITLE
[Possible mod conflicts] Pipez forgetting connection to mekanism multi-structure tanks

### ISSUE THREAD

**Issue by jarquafelmu** [Meldexun/EntityCulling#29]
Issue is reported here:
henkelmax/pipez#50

It's my belief that entity culling might be involved because this only happens when I am not looking at the connections

**Comment by Meldexun** [comment]
So the bug you are reporting is not only a visual bug, right?
If that is the case then Entity Culling has nothing to do with this as Entity Culling only changes rendering and not the behavior of blocks/tile entities/entities/etc.
