### ISSUE TITLE
v2.0.0 crashes game during startup with Optifine

### ISSUE THREAD

**Issue by TCreopargh** [Meldexun/EntityCulling#3]
**Describe the bug**
V2.0 crashes the game during startup
Using optifine HD_U_F6_Pre1 (tried F5, it crashes as well)
version before v2.0 work fine

**To Reproduce**
1. Install v2.0.0 of this mod
2. install optifine HD_U_F6_Pre1
3. launch the game
4. Boom, it crashes

**Expected behavior**
It doesn't crash

**Screenshots**

**Versions**
Entity Culling: 2.0.0
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report: https://paste.ubuntu.com/p/vrMQjdfbvb/
Latest log (upload as a file):
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Optifine
Other mods (that are also installed): see crash report

**Comment by Ameranth** [comment]
I am running 2.0 with many mods as well, and it is not crashing; I'd recommend trying a binary search to figure out which mod is conflicting :S

**Comment by TCreopargh** [comment]
> I am running 2.0 with many mods as well, and it is not crashing; I'd recommend trying a binary search to figure out which mod is conflicting :S

Hmm binary search is not necessary if it's obviously conflicting with mods that screw up the rendering (like optifine, better foliage, particle culling etc. also my pack has 500+ mods that takes 10+ mins to launch and a binary search will take days if unlucky :/) I'll try with these mods later

**Comment by Ameranth** [comment]
Oh wow, yeah probably try with the more likely ones first, then, heh.
If it helps any I am running on 1.12.2 with better foliage, optifine as well, though of course settings within those will likely wildly vary.

**Comment by TCreopargh** [comment]
UPDATE: This bug has been identfied, The bug is caused by **Optifine**. Tried both F5 and F6_pre1 on a clean modpack and both crashed the game. Uninstalling optifine resolves it.

**Comment by Meldexun** [comment]
How did you install optifine? (You should just throw it into the mods folder)

**Comment by TCreopargh** [comment]
I installed it with a custom minecraft launcher but that shouldn't make any difference

**Comment by Meldexun** [comment]
Entity Culling checks the mods folder for a file with "OptiFine" in it's name and the ".jar" extension.

**Comment by TCreopargh** [comment]
There's no such file in my mod folder. let me figure out how it's installed, hold on

**Comment by TCreopargh** [comment]
It's installed into .minecraft\libraries

**Comment by Meldexun** [comment]
Optifine has to be in the same folder as Entity Culling. Otherwise it won't work. (I might think about another way to detect optifine in the future but that has low priority since there is a way to both mods work together)

**Comment by TCreopargh** [comment]
I think there should be other ways to look for a mod's jar file rather than searching for it in the mods folder.
I've seen other mods that once do it but fixed it, like https://www.curseforge.com/minecraft/mc-mods/dupefix-project
maybe you can try to read his code?

**Comment by Meldexun** [comment]
I updated the optifine detection in v2.0.1. Maybe that helps?

**Comment by TCreopargh** [comment]
It's working, thanks!
