### ISSUE TITLE
[1.12.2] Fairy Lights don't render

### ISSUE THREAD

**Issue by xJon** [Meldexun/EntityCulling#31]
**Describe the bug**
As the title describes. Reported to my modpack over https://github.com/xJon/The-1.12.2-Pack/issues/697

**Screenshots**
https://i.imgur.com/qhRvsrQ.mp4

**Versions**
Entity Culling: `4.1.5`
Forge: `14.23.5.2855`
Minecraft: `1.12.2`
Fairy Lights: `2.2.0`

**Comment by Neamow** [comment]
Is there any update on this? Fairy lights still don't render if they're in a modpack with Entity Culling.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-4.2.1
