### ISSUE TITLE
[1.12.2 4.1.5] Crash on startup "Inconsistent stackmap frames at branch target"

### ISSUE THREAD

**Issue by SpencerMeow** [Meldexun/EntityCulling#35]
On the latest 1.12.2 version the game won't start

[crash-2021-10-30_11.53.11-client.txt](https://github.com/Meldexun/EntityCulling/files/7447174/crash-2021-10-30_11.53.11-client.txt)

**Comment by Meldexun** [comment]
Use the issue template and a supported optifine version (preview versions are not supported)
