### ISSUE TITLE
Ancient Warfare 2 gates/drawbridges do not render if the bottom is not on-screen

### ISSUE THREAD

**Issue by bluejello42** [Meldexun/EntityCulling#37]
**Describe the bug**
Ancient warfare gates/drawbridges do not render if the bottom bottom row is not on-screen (specifically the one block on the bottom that has a NBT tag "render")

I suspect this is going to be on AW to fix, the block with the render tag is "ancientwarfarestructure:gate_proxy_tile", which makes up the gate/drawbridge, setting the render tag to 1 on any block in the gate/drawbridge causes the full thing to render if that block is on-screen.

this issue occurs even if "skipHiddenEntityRendering" and "SkipHiddenTileEntityRendering" is set to false, and trying various tags for tile entities or entitie blacklists have not worked (ancientwarfarestructure:aw_gate, ancientwarfarestructure:gate_proxy_tile)

**To Reproduce**
1. place a AW gate/drawbridge
2. Look at the gate/drawbridge, then look up

**Expected behavior**
The gate/drawbridge stays rendered

**Screenshots**
with bottom row in view
![image_2021-11-14_120503](https://user-images.githubusercontent.com/75703767/141694828-c2741054-627d-44b8-9932-39879e5fa0e7.png)
without
![image_2021-11-14_120524](https://user-images.githubusercontent.com/75703767/141694834-45c504c2-bae0-4101-906b-c5d77392f715.png)

**Versions**
Entity Culling: 4.1.5
Forge: 14.23.5.2855
Minecraft: 1.12

**Other**
Other mods (that are necessary to produce the bug): Ancient warfare 2

**Comment by Meldexun** [comment]
Fixed in v1.12.2-4.2.1
