### ISSUE TITLE
Hangs with Netty errors

### ISSUE THREAD

**Issue by TheBowman42** [Meldexun/EntityCulling#38]
**Describe the bug**
I have a lot going on when this happens, so it makes it hard for me to narrow down what I'm doing to cause it. The abridged version is I ignite TNT to spawn a lycanites mob and summon another lycanites mob to fight it. Eventually it kicks me out of my single player world, freezes or crashes to desktop.

**To Reproduce**
1. Repeatedly create explosions to spawn mobs
2. Spawn more mobs with lycanites summoning blocks
3. Wait

**Expected behavior**
Continued gameplay

**Versions**
Entity Culling: EntityCulling-1.12.2-4.2.0-dev5.7
Forge: 14.23.5.2838
Minecraft: 1.12.2

**Other**
Crash report (upload as a file): None produced
Latest log (upload as a file):[latest.log](https://github.com/Meldexun/EntityCulling/files/7548059/latest.log)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Probably lycanitesmobs
Other mods (that are also installed): There's a boat load of them, so it's in the details below. <details>
# LibLoader.jar
AdHooks-1.12.2-3.3.0.0-build.0528.jar
Advanced-Fishing-1.12.2-1.3.3.jar
AIReducer-1.12.2-0.3.0-preB.jar
alcatrazcore-1.0.4.jar
antiqueatlas-1.12.2-4.6.3.jar
anvilpatch-1.1.0.jar
Aquaculture-1.12.2-1.6.8.jar
armorunder-mc1.12.2-1.0.0.jar
astikorcarts-1.12.2-0.1.2.8.jar
AutoRegLib-1.3-32.jar
BacoDifficulty-1.0.3.jar
base-1.12.2-3.14.0.jar
BattleTowers-1.12.2.jar
Baubles-1.12-1.5.2.jar
BedBreakBegone-1.0.0.jar
bettercaves-1.12.2-2.0.4.jar
BetterCombat-1.12.2-1.5.6.jar
BetterFoliage-MC1.12-2.3.3.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
betternether-0.1.8.6.jar
BetterQuesting-3.5.329.jar
BetterTabs-1.0.2.jar
better_survival-1.4.1.jar
Bloodmoon-MC1.12.2-1.5.3.jar
BNBGamingLib-1.12.2-2.17.6.jar
Born In A Barn V1.8-1.12-1.1.jar
Bountiful Baubles-1.12.2-0.1.6.jar
Bountiful-2.2.3-preG.jar
BQTweaker-1.2.1.jar
BQ_Multiblock_Structure_Integration-1.0.6.jar
callablehorses-1.12.2-1.1.jar
campfire-1.12-v1.2.jar
carrotslib-mc1.12.2-1.0.0b1.jar
carryon-1.12.2-1.12.6.20.jar
Charm-1.12.2-1.4.1.jar
ChunkAnimator-MC1.12-1.2.jar
classyhats-1.6.0.jar
_MixinBootstrap-1.1.0.jar
[___MixinCompat-0.8___].jar
CollisionDamage-1.2.1.jar
comforts-1.12.2-1.4.1.3.jar
CompatSkills-1.12.2-1.17.0.jar
ContentTweaker-1.12.2-4.10.0.jar
Controlling-3.0.8.jar
CoralReef-2.5-1.12.2.jar
corpsecomplex-1.12.2-1.0.12.0.jar
craftablechainmail-1.0.jar
CraftableHorseArmour-1.3.0-1.12.jar
CraftTweaker2-1.12-4.1.20.669.jar
CreativeCore_v1.10.65_mc1.12.2.jar
CustomMainMenu-MC1.12.2-2.0.9.1.jar
defiledlands-1.12.2-1.4.3.jar
disenchanter-[1.12]1.7.jar
DoomlikeDungeons-1.14.10-MC1.12.2.jar
DynamicSurroundings-1.12.2-3.6.1.0.jar
DynamicSurroundingsHuds-1.12.2-3.6.0.0.jar
DynamicTrees-1.12.2-0.9.25.jar
dynamictreesdefiledlands-1.12.2-1.0.0.jar
DynamicTreesTraverse-1.12.2-2.1.jar
ElenaiDodge-1.12.2-2.0.jar
EnchantmentDescriptions-1.12.2-1.1.20.jar
EnhancedVisuals_v1.4.3_mc1.12.2.jar
EntityCulling-1.12.2-4.2.0-dev5.7.jar
FamiliarFauna-1.12.2-1.0.11.jar
FancyBlockParticles-1.12.x-2.4.1.jar
FantasticLib-1.12.2.047.jar
firstaid-1.6.18-test2.jar
FishingMadeBetter-1.12.2-2.1.4.jar
foamfix-0.10.14-1.12.2.jar
FoodExpansion1.3.3-1.12.2.jar
ForgeEndertech-1.12.2-4.5.6.0-build.0619.jar
Forgelin-1.8.4.jar
ForgottenItems MC1.12.2 v1.2.1.jar
FriendlyEndermite_v1.0.1_mc1.12.2.jar
FullscreenWindowed-1.12-1.6.0.jar
fxcontrol-1.12-0.1.15.jar
GlobalGameRules-1.12.2-2.2.7.jar
GooglyEyes-1.12.2-7.1.1.jar
Grapplemod-v12-1.12.2 (v2).jar
iceandfire-1.7.1-1.12.2.jar
iChunUtil-1.12.2-7.2.2.jar
incontrol-1.12-3.9.18.jar
InfernalMobs-1.12.2.jar
Inspirations-1.12.2-0.2.9.jar
InventoryTweaks-1.64+dev.151.jar
ISeeDragons-1.2.jar
ItemPhysic_Full_1.4.37_mc1.12.2.jar
itlt-1.12.x-1.0.4.jar
IvToolkit-1.3.3-1.12.jar
jei_1.12.2-4.16.1.302.jar
Level Up! 2-1.1.23-1.12.jar
librarianlib-1.12.2-4.22.jar
llibrary-1.7.20-1.12.2.jar
LoadingScreens-1.12.2-0.3.1.jar
Locks-Backport-preW-B.jar
LootTweaker-0.3.1+MC1.12.2.jar
lostcities-1.12-2.0.22.jar
lycanitesmobs-1.12.2-2.0.8.3-BETA05.jar
MainMenuScale-1.3.2.jar
Mantle-1.12-1.3.3.55.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
MmmMmmMmmMmm-1.12-1.14.jar
MoBends_1.12.2-1.1.0-28.09.21.jar
modtweaker-4.0.20.5.jar
MouseTweaks-2.10.1-mc1.12.2.jar
MTLib-3.0.7.jar
MultiMine-1.12.2.jar
Neat 1.4-17.jar
notreepunching-2.0.21.jar
OptiFine_1.12.2_HD_U_G5.jar
OreLib-1.12.2-3.6.0.1.jar
particleculling-1.12.2-v1.2.jar.disabled
phosphor-1.12.2-0.2.6+build50-universal.jar
pigstep-1.12.jar
Placebo-1.12.2-1.6.0.jar
PotionCore-1.9_for_1.12.2.jar
PotionFingers-r1.0-8.jar
QualityTools-1.0.7_for_1.12.2.jar
Quark-r1.6-179.jar
RealBench-1.12.2-1.3.3.jar
RealisticTorches-1.12.2-2.1.2.jar
RebornCore-1.12.2-3.19.5-universal.jar
RecurrentComplex-1.4.8.2.jar
Reskillable-1.12.2-1.13.0.jar
ResourceLoader-MC1.12.1-1.5.3.jar
RLTweaker-1.12.2-0.4.3-preY.jar
RoguelikeDungeonsFnarEdition-1.12.2-2.4.1-snapshot.jar
roughTweaks0.2.4-1.12.2.jar
Ruins-1.12.2.jar
rustic-1.1.7.jar
sampler-1.84.jar
ScalingHealth-1.12.2-1.3.42+147.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SetBonus-1.12.2.020.jar
ShieldBreak-1.0.1.jar
SilentLib-1.12.2-3.0.14+168.jar
SimpleDifficulty-1.12.2-0.3.7-preN.jar
sit-1.12.2-v1.3.jar
SnowRealMagic-1.12.2-0.5.5.jar
SoManyEnchantments-0.5.3-preF-prottest.jar
SoundFilters-0.12.1_for_1.12.jar
spartanfire-0.05.jar
SpartanHUDBaubles-1.12.2-1.0.0-indev-4.jar
SpartanShields-1.12.2-1.5.4.jar
SpartanWeaponry-1.12.2-1.4.0-indev-13.jar
SpawnerControl-1.6.3b.jar
SRParasites-1.12.2v1.9.1.jar
StandardExpansion-3.4.173.jar
switchbow-1.6.5.jar
TickProfiler-1.12-0.0.10.jar
tnt_utilities-mc1.12-1.2.3.jar
Toast Control-1.12.2-1.8.1.jar
ToolBelt-1.12.2-1.9.14.jar
Traverse-1.12.2-1.6.0-69.jar
Trinkets and Baubles-0.31-Pre-Release-Beta-33.jar
trumpetskeleton-1.12-1.0.2.1.jar
tschipplib-1.12.2-1.1.7.jar
tumbleweed-1.12-0.4.7.jar
VariedCommodities_1.12.2-04Nov21snapshot6.jar
Waystones_1.12.2-4.1.0.jar
WearableBackpacks-1.12.2-3.1.4.jar
wolfarmor-1.12.2-3.7.5-universal-signed.jar
XPFromHarvest-1.12.2-1.2.0.jar
xptome-1.12.2-v1.1.6.jar
YungsLaw-1.12.2-1.0.4.jar
</details>

**Comment by Meldexun** [comment]
This is an issue of LycanitesMobs. I reported it to them.
