### ISSUE TITLE
[1.12] Vivecraft crashes when using it with this mod

### ISSUE THREAD

**Issue by trollxslaya** [Meldexun/EntityCulling#39]
**Describe the bug**
Game crashes when using this with Vivecraft 1.12.2

**To Reproduce**
1. Install Vivecraft and make sure to check the "Install Vivecraft with Forge" box
2. Put the EntityCulling mod into your main mods folder
3. Launch Minecraft
4. If it doesn't crash then try going into a world

**Expected behavior**
The game should not be crashing at all.

**Screenshots**

**Versions**
Entity Culling: Every 1.12.2 version
Forge: Every 1.12.2 version
Minecraft: 1.12.2

**Other**
Crash report (upload as a file): I can't really do this because for some reason my vr headset isnt detecting and I just thought of this crash again when I wanted to improve performance.
Latest log (upload as a file): Same thing (If you need me to try and get this to work I will but I've read online that this mod is incompatible with Vivecraft 1.12.2 for other people as well).
Singleplayer/Multiplayer: Before this
Other mods (that are necessary to produce the bug): Vivecraft
Other mods (that are also installed): Optifine

**Comment by Meldexun** [comment]
1. Don't use terms like 'every' or 'latest' when talking about versions. Often enough people think they use the latest version or tested all versions but they didn't.
2. Without a crashreport this can't be worked on.

**Comment by quentin452** [comment]
maybe its normal , its a vr mod :D Vivecraft

**Comment by Meldexun** [comment]
Closing this now as the used version of EntityCulling is very outdated now.
