### ISSUE TITLE
[compatibility, 1.12.2] Ice and Fire Flying Dragons

### ISSUE THREAD

**Issue by Ameranth** [Meldexun/EntityCulling#4]
**Describe the bug**
[Ice and Fire](https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons/files/2939529) dragons are culled _while flying_, even if added to culling blacklists, and even if entity/tile entity culling is disabled. Disabling the "enabled" option in config _does_ allows them to render, however.

**To Reproduce**
1. Find or spawn a stage 3 or higher IaF dragon, it will be culled _once it flies_.

**Expected behavior**
Dragons should not be culled while flying, especially since they are larger than 3 blocks and added to the entity blacklist.

**Versions**
Entity Culling: 2.0
Forge: 14.23.5.2854
Minecraft: 1.12.2
Optifine: 1.12.2_HD_U_F5

Thank you for your time!

**Comment by Meldexun** [comment]
Should be fixed in v2.0.1

**Comment by Ameranth** [comment]
Indeed it is, thank you very much!
