### ISSUE TITLE
[1.12.2] Techguns(?) client crash

### ISSUE THREAD

**Issue by Aeron216** [Meldexun/EntityCulling#41]
**Describe the bug**
Client crash when traveling to another dimension. I came here since the report log printed this:
```
java.lang.IllegalAccessError: Please report this to EntityCulling!
```

**To Reproduce**
1. Went to another dimension. From the **Erebus** to the Overworld. Specifically by going through the roof of the Erebus by using **Vertically Stacked Dimensions**, instead of a portal.

**Expected behavior**
To not crash on dimension travel.

**Versions**
Entity Culling: 4.2.1
Forge: 2854
Minecraft: 1.12.2

**Other**
Crash report (upload as a file): [crash-2021-12-04_23.26.23-client.txt](https://github.com/Meldexun/EntityCulling/files/7655281/crash-2021-12-04_23.26.23-client.txt)
Latest log (upload as a file): https://www.dropbox.com/s/991rc03t1dg11xv/latest.log?dl=0

Singleplayer/Multiplayer: Happened while playing in a server, only my client crashed.

Other mods (that are necessary to produce the bug): Techguns is the suspected mod according to the crash log. 
Specifically, its Reaction Chamber multiblock.

Other mods (that are also installed): This is part of an unreleased modpack. Full list: [mod-list_2021-11-06_05.39.49.txt](https://github.com/Meldexun/EntityCulling/files/7655286/mod-list_2021-11-06_05.39.49.txt)

Instantly crashed once again after trying to log back into the server. Stopped crashing on the next login.

**Comment by Aeron216** [comment]
Happened again this morning.

https://gist.github.com/Aeron216/73eb2020b04c8f3c233c4765d087fe08

I'll try blacklisting Techguns blocks/tiles and see how it goes.

**Comment by Aeron216** [comment]
I have to add that I recently upgraded to version 4.2.1.
I ran 4.1.5 for several months and nothing ever went wrong.

**Comment by Aeron216** [comment]
I did one more test before trying to blacklist Techguns blocks.

Switched from GraalVM back to Hotspot
Downgraded Optfines G6 preview to G5. Since I just read that you do not give support for preview versions.
Still using 4.2.1:

Same client crash.
https://gist.github.com/Aeron216/12f478979592815b0815842779b37508

**Comment by Aeron216** [comment]
Last update

I could not figure out how to blacklist Techguns **machines/tiles** so I went back to 4.1.5 for now.

**Comment by Meldexun** [comment]
EntityCulling v1.12.2-4.2.3 should fix this.

**Comment by Meldexun** [comment]
Actually EntityCulling v1.12.2-4.2.3 does **not** fix this.
But EntityCulling v1.12.2-4.2.4 should.
