### ISSUE TITLE
[1.12.2] Fairy Lights don't render if hung on fences using 4.2.1

### ISSUE THREAD

**Issue by xJon** [Meldexun/EntityCulling#45]
**Describe the bug**
First reported over https://github.com/xJon/Hexxit-II/issues/78.

**To Reproduce**
1. Install Fairy Lights & Entity Culling
2. Try to hang fairy lights between 2 fences.

**Screenshots**
![image](https://user-images.githubusercontent.com/8945347/145693184-ff38b0fb-fbfe-4bf2-8a6f-b195e3cf258b.png)

**Versions**
Entity Culling: `4.2.1`
Forge: `14.23.5.2859`
Minecraft: `1.12.2`

**Other**
Singleplayer/Multiplayer: Both
Other mods (that are necessary to produce the bug): `Fairy Lights`

Thank you!

**Comment by Meldexun** [comment]
Fixed in v1.12.2-4.2.3

**Comment by xJon** [comment]
Thank you so much!
