### ISSUE TITLE
[Crash] Incompatibility with Valkyrien Skies

### ISSUE THREAD

**Issue by gatoborrachon** [Meldexun/EntityCulling#46]
**Describe the bug**
When you try to assemble a Valkyrien Skies' Ship with EntityCulling installed, you will get a crash

**To Reproduce**
1. Build a simple ship in the air using any block you want
![2021-10-23_17 55 31](https://user-images.githubusercontent.com/61126174/138573944-0f53fd4f-e214-4a5c-8bd2-65e9bf0e23d8.png)

2. Place the blocks called "Physics Infuser" and "Captain's Chair" over the ship, and then, put the item called "Physics Core" inside the "Physics Infuser"
1.- Physics Infuser and Captain's Chair
![2021-10-23_17 55 45](https://user-images.githubusercontent.com/61126174/138573951-e4420682-654f-4d75-a463-9b658e09efca.png)

2.- "Physics Core" inside the "Physics Infuser"
![2021-10-23_17 55 57](https://user-images.githubusercontent.com/61126174/138573958-5cbcc431-f90a-40fd-8251-86d0b454f95c.png)

3. Try to Assemble this ship with the "Physics Infuser" by clicking the "Assemble Ship" Buttom
![2021-10-23_17 56 01](https://user-images.githubusercontent.com/61126174/138573978-1f6b523e-aa04-467f-9ad7-7972ac7e75b1.png)

4. See crash

**Expected behavior**
No crash

**Versions**
Entity Culling: 4.2.5
Forge: 14.23.5.2860
Minecraft: 1.12.2
Valkyrien Skies Core: [1.1.7](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies/files/3286262)
Valkyrien Skies World: [1.0.0](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies-world/files/3061764)
Valkyrien Skies Control: [1.1.1](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies-control/files/3160203)

**Other**
Crash report (upload as a file): [crash-2021-12-24_20.05.47-client.txt](https://github.com/Meldexun/EntityCulling/files/7775370/crash-2021-12-24_20.05.47-client.txt)
Latest log (upload as a file): [latest.log](https://github.com/Meldexun/EntityCulling/files/7775371/latest.log)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): [Valkyrien Skies Core](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies), [Valkyrien Skies World](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies-world) and [Valkyrien Skies Control](https://www.curseforge.com/minecraft/mc-mods/valkyrien-skies-control)
Other mods (that are also installed): Nothing more
Additional Notes: 
1.- Downgrading to EntityCulling 4.1.5 fixes the issue, if i use EntityCulling 4.2.1 i get the same [crash](https://github.com/Meldexun/EntityCulling/files/7775387/crash-2021-12-24_20.18.15-client.txt)
2.- I know that messing with Valkyrien Skies might be a pain in the rear, so if the issue has no (easy) fix from your side, no problem, i will continue using 4.1.5, thanks anyways

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.0.1
