### ISSUE TITLE
[1.12.2] Some flickering

### ISSUE THREAD

**Issue by TheSnowyChickens** [Meldexun/EntityCulling#47]
Hello,
as you told me on Curse, here is now the Git issue. :)

**Describe the bug**
Some overlays, like EIO travel anchors, starts to flicker. 

**To Reproduce**
1. Place some travel anchors
2. look at the travel anchors through some walls

**Expected behavior**
A clean view.

**Video**
https://drive.google.com/file/d/1qA4mUoouDjNMil744o7K0k0KRVc4Wd_x/view?usp=sharing

**Versions**
Entity Culling: 4.2.5
Forge: 2860
Minecraft: 1.12.2

**Other**
Singleplayer/Multiplayer: Multiplayer

Other mods (that are necessary to produce the bug): I have Optifine, but Optifine caused no problems with EC with v4.1.5.

Other mods (that are also installed): I don't think any of these mods can cause the issue, because they all worked fine with v4.1.5.
![grafik](https://user-images.githubusercontent.com/29357962/147749900-fc80fc2d-f562-4498-9d24-154e2596070e.png)

**Comment by Meldexun** [comment]
Have you tried adding the EIO travel anchors to the `skipHiddenEntityRenderingBlacklist` config option?

**Comment by TheSnowyChickens** [comment]
No, but I can do this now. :D
(thx for the tip)

How is the format for the bracket ?
<"enderio:travel_anchor"> or <enderio:travel_anchor> and with or without , or ; after the name ?

**Comment by Meldexun** [comment]
You can use the ingame config gui.

**Comment by TheSnowyChickens** [comment]
Ah okay.
Next question: is a game restart required ? (1.12.2 modpacks are so slow in loading, asking you is faster :D )

**Comment by Meldexun** [comment]
The registry name of the travel anchor is `enderio:tile_travel_anchor`.

No you can only disable specifc entities or tile entities.

**Comment by Krutoy242** [comment]
Please add `enderio:tile_travel_anchor` into default blacklist, because it took me about 20 days to found a problem 😅
