### ISSUE TITLE
[Issue] render issue with OpenBlocks' Crayons

### ISSUE THREAD

**Issue by gatoborrachon** [Meldexun/EntityCulling#5]
**Describe the bug**
when you try to place a Crayon block from OpenBlocks it is not rendered at all
(check this short video if you don't remember how to use it)
https://www.youtube.com/watch?v=DaohT0njNko

**To Reproduce**
1. Put goggles of the same color as the crayon
2. try to put some blocks with the crayon
3. See error

**Expected behavior**
the crayon blocks will not be rendered.

**Screenshots**
With Entity Culling (you can see the hitbox of the block, but not the block):
![2020-12-18_00 07 33](https://user-images.githubusercontent.com/61126174/102581937-2f3b0a00-40c7-11eb-8d26-3221b2f3df53.png)

Without Entity Culling:
![2020-12-18_00 22 14](https://user-images.githubusercontent.com/61126174/102581944-319d6400-40c7-11eb-913e-c525f0ae00be.png)

**Versions**
Entity Culling: 2.0.2
OpenBlocks: 1.8.1
OpenModsLib: 0.12.2
Forge: 14.23.5.2854
Minecraft: 1.12.2

**Other**
Latest log with Entity Culling:
[2020-12-18-1.log](https://github.com/Meldexun/EntityCulling/files/5714006/2020-12-18-1.log)

Latest log without Entity Culling:
[latest.log](https://github.com/Meldexun/EntityCulling/files/5714011/latest.log)

Singleplayer
Other mods (OpenBlocks):

this maybe is an issue from OpenBlocks side right? what i would need to edit in it to fix this?

**Comment by Meldexun** [comment]
Should be fixed in v2.0.4

**Comment by gatoborrachon** [comment]
i confirm this, it's fixed
