### ISSUE TITLE
[1.12.2]Install to RLCraft modpack, crash

### ISSUE THREAD

**Issue by EnterFor** [Meldexun/EntityCulling#50]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions**
Entity Culling:4.2.5
Forge:2860
Minecraft:1.12.2

**Other**
Latest log (upload as a file):
https://paste.ubuntu.com/p/fPHmtfVbZN/

**Comment by Meldexun** [comment]
Don't download mods from third party sites.
Don't install mods twice.
