### ISSUE TITLE
[1.12.2] Visual/Camera Bug When Using Shaders

### ISSUE THREAD

**Issue by angeerey** [Meldexun/EntityCulling#52]
**Describe the bug**
A full third-person body is shown in first person when you use any shader, with your camera inside of your own head.

**To Reproduce**
1. Select any shader of choice
2. Go into first-person and the bug should show

**Screenshots/Videos**
https://imgur.com/a/bXusNCs

**Versions**
Entity Culling: Entity Culling: 5.0.1
Forge: 1.12.2-forge-14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): No other mods are needed, just entity culling and optifine.

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:
**There was no crash when encountering this bug, but if there is a way to get a log file without it crashing then I am not sure how.**

**Comment by SticksS123** [comment]
same issue

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.0.2
