### ISSUE TITLE
[1.12.2] Incompatibility with Jurassic World Reborn

### ISSUE THREAD

**Issue by JonCris** [Meldexun/EntityCulling#53]
**Describe the bug**
Makes all Entities of Jurassic World Reborn Invisible

**To Reproduce**
Spawn any Dino from the mod Jurassic World Reborn

**Versions**
Entity Culling: 1.12.2-5.0.2.jar
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):  [Jurassic World Reborn] (https://www.curseforge.com/minecraft/mc-mods/jurassic-world-reborn-mod)

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.1.0
