### ISSUE TITLE
[1.12.2] Flickering with Giant Chance Cube

### ISSUE THREAD

**Issue by JonCris** [Meldexun/EntityCulling#54]
**Describe the bug**
Giant Chance Cube Flickers from multiple sides. 

**To Reproduce**
Use command to spawn Giant Chance Cube: /CCubes spawnGiantCube X Y Z

**Screenshots/Videos**
![flick](https://user-images.githubusercontent.com/8162795/154824937-0d674942-fa59-4510-bc87-06acad668e2a.gif)

**Versions**
Entity Culling: [1.12.2-5.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/entity-culling/files/3653009)
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods: [ChanceCubes 1.12.2-5.0.2.385](https://www.curseforge.com/minecraft/mc-mods/chance-cubes/files/3087611)

**Comment by Meldexun** [comment]
This is a bug in the ChanceCubes mod. They should fix the render bounding box of this tile entity to cover the complete tile entity.

You can enable `debugRenderBoxes` in the EntityCulling config to view the render bounding boxes. Then you can change the render bounding box of the giant chance cube with the
`EntityCulling config` - > `entity` - > `entityBoundingBoxGrowthList`
config option.
Adding this to the mentioned config option should work `chancecubes:tilechancegiant=1,1,1` (maybe you have to change the numbers a bit).

**Comment by Meldexun** [comment]
Aside from other mods being bugged, this shouldn't be a problem anymore in v1.12.2-5.2.0
