### ISSUE TITLE
Crash on entering world

### ISSUE THREAD

**Issue by democat3457** [Meldexun/EntityCulling#55]
**Describe the bug**
After updating EntityCulling from 4.2.5 to 5.1.0, the game crashes upon entering any world, including newly created ones.

**To Reproduce**
1. Use 5.1.0.
2. Enter any world.
3. Observe that game crashes after loading the world.

**Versions**
Entity Culling: 5.1.0
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): Unsure, but the crash report doesn't seem to mention any other mod in the stacktrace.

**Log File**
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here:

https://gist.github.com/democat3457/cedb9f844f67762fc77c8e0ea832372c

**Comment by WolfBV** [comment]
It's trying to use opengl 4.4 instead of falling back to the old raytracing based culling.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.1.1
