### ISSUE TITLE
Another Crash with Valkyrien Skies

### ISSUE THREAD

**Issue by metocolipson1** [Meldexun/EntityCulling#58]
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-03-11 11:08:08 EST
Description: Culling Thread crashed!

org.valkyrienskies.mod.common.util.multithreaded.CalledFromWrongThreadException: Wrong thread calling code: Thread[Culling Thread,10,main]
    at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.enforceGameThread(WorldClientShipManager.java:38)
    at org.valkyrienskies.mod.common.ships.ship_world.WorldClientShipManager.getPhysObjectFromUUID(WorldClientShipManager.java:106)
    at org.valkyrienskies.mod.common.util.ValkyrienUtils.lambda$getPhysoManagingBlock$0(ValkyrienUtils.java:66)
    at java.util.Optional.map(Optional.java:215)
    at org.valkyrienskies.mod.common.util.ValkyrienUtils.getPhysoManagingBlock(ValkyrienUtils.java:66)
    at net.minecraft.tileentity.TileEntity.getDistanceSq(TileEntity.java:628)
    at meldexun.entityculling.util.CullingThread.checkTileEntityVisibility(CullingThread.java:231)
    at meldexun.entityculling.util.CullingThread.updateTileEntityCullingState(CullingThread.java:156)
    at meldexun.entityculling.util.CullingThread.run(CullingThread.java:115)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.15.7
  Java Version: 1.8.0_74, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 3886070800 bytes (3706 MB) / 8509456384 bytes (8115 MB) up to 8509456384 bytes (8115 MB)
  JVM Flags: 25 total; -Xmx8G -Xms8G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=25 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:ParallelGCThreads=10
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 LoliASM 4.6 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 101 mods loaded, 101 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version                 | Source                                            | Signature                                |
       |:------ |:-------------------- |:----------------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2                  | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                  | 9.42                    | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                  | 8.0.99.99               | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2854            | forge-1.12.2-14.23.5.2854.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | creativecoredummy    | 1.0.0                   | minecraft.jar                                     | None                                     |
       | LCHIJA | ivtoolkit            | 1.3.3-1.12              | minecraft.jar                                     | None                                     |
       | LCHIJA | otgcore              | 1.12.2 - v8.3           | minecraft.jar                                     | None                                     |
       | LCHIJA | mixinbooter          | 4.1                     | minecraft.jar                                     | None                                     |
       | LCHIJA | obfuscate            | 0.2.6                   | minecraft.jar                                     | None                                     |
       | LCHIJA | dsurroundcore        | 3.5.4.3                 | minecraft.jar                                     | None                                     |
       | LCHIJA | valkyrienskies       | 1.1.7                   | [[[[[[[[[valkyrien-skies-1.1.7-all]].jar          | None                                     |
       | LCHIJA | ambience             | 1.7.3                   | Ambience-1.12.2-1.7.3.jar                         | None                                     |
       | LCHIJA | aoa3                 | 3.3.2                   | AoA3-3.3.2.jar                                    | 8bddeac148843f40e0b9f69201be2f4b3071700d |
       | LCHIJA | placebo              | 1.6.0                   | Placebo-1.12.2-1.6.0.jar                          | None                                     |
       | LCHIJA | apotheosis           | 1.12.4                  | Apotheosis-1.12.2-1.12.5.jar                      | None                                     |
       | LCHIJA | astikorcarts         | 1.12.2-0.1.2.7          | astikorcarts-1.12.2-0.1.2.7.jar                   | None                                     |
       | LCHIJA | jei                  | 4.15.0.291              | jei_1.12.2-4.15.0.291.jar                         | None                                     |
       | LCHIJA | quark                | r1.5-168                | Quark-r1.5-168.jar                                | None                                     |
       | LCHIJA | autoreglib           | 1.3-32                  | AutoRegLib-1.3-32.jar                             | None                                     |
       | LCHIJA | baubles              | 1.5.2                   | Baubles-1.12-1.5.2.jar                            | None                                     |
       | LCHIJA | thaumcraft           | 6.1.BETA26              | Thaumcraft-1.12.2-6.1.BETA26.jar                  | None                                     |
       | LCHIJA | botania              | r1.10-361               | Botania+r1.10-361.jar                             | None                                     |
       | LCHIJA | bountifulbaubles     | 0.0.1                   | Bountiful+Baubles-1.12.2-0.1.5.jar                | None                                     |
       | LCHIJA | bmtr                 | 0.4                     | BringMeTheRings-0.4.jar                           | None                                     |
       | LCHIJA | caz_fps_mod_1122     | 1.12.2                  | cazfps_landscape_SPARCLE_1.12.2.jar               | None                                     |
       | LCHIJA | cgm                  | 0.15.3                  | cgm-0.15.3-mc1.12.2.jar                           | None                                     |
       | LCHIJA | extendedrenderer     | v1.0                    | coroutil-1.12.1-1.2.32.jar                        | None                                     |
       | LCHIJA | coroutil             | 1.12.1-1.2.32           | coroutil-1.12.1-1.2.32.jar                        | None                                     |
       | LCHIJA | configmod            | v1.0                    | coroutil-1.12.1-1.2.32.jar                        | None                                     |
       | LCHIJA | corpse               | 1.12.2-1.0.8            | corpse-1.12.2-1.0.8.jar                           | None                                     |
       | LCHIJA | craftstudioapi       | 1.0.0                   | CraftStudio-1.0.0.93-mc1.12-alpha.jar             | None                                     |
       | LCHIJA | enhancedvisuals      | 1.3.0                   | EnhancedVisuals_v1.3.11_mc1.12.2.jar              | None                                     |
       | LCHIJA | creativecore         | 1.10.0                  | CreativeCore_v1.10.16_mc1.12.2.jar                | None                                     |
       | LCHIJA | customnpcs           | 1.12                    | CustomNPCs_1.12.2-24Jan21snapshot.jar             | None                                     |
       | LCHIJA | damagetilt           | 0.1.0                   | DamageTilt-1.12.2-0.1.0.jar                       | None                                     |
       | LCHIJA | ptrmodellib          | 1.0.5                   | PTRLib-1.0.5.jar                                  | None                                     |
       | LCHIJA | props                | 2.6.3.7                 | Decocraft-2.6.3.7_1.12.2.jar                      | None                                     |
       | LCHIJA | dimdoors             | 1.12.2-3.1.2+UNOFFICIAL | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar      | None                                     |
       | LCHIJA | lootablebodies       | 2.4.0                   | DrCyanosLootableBodies_1.12-2.4.0.jar             | None                                     |
       | LCHIJA | dynamictrees         | 1.12.2-0.9.6            | DynamicTrees-1.12.2-0.9.6.jar                     | None                                     |
       | LCHIJA | effortlessbuilding   | 1.12.2-2.16             | effortlessbuilding-1.12.2-2.16.jar                | None                                     |
       | LCHIJA | enchdesc             | 1.1.20                  | EnchantmentDescriptions-1.12.2-1.1.20.jar         | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | redstoneflux         | 2.1.1                   | RedstoneFlux-1.12-2.1.1.1-universal.jar           | None                                     |
       | LCHIJA | p455w0rdslib         | 2.3.161                 | p455w0rdslib-1.12.2-2.3.161.jar                   | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | endermanevo          | 1.0.33                  | EndermanEvolution-1.12.2-1.0.33.jar               | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCHIJA | entityculling        | 5.2.0                   | EntityCulling-1.12.2-5.2.0.jar                    | None                                     |
       | LCHIJA | erebus               | 1.0.30                  | Erebus-1.0.30.jar                                 | None                                     |
       | LCHIJA | eyesinthedarkness    | 0.0.5                   | EyesInTheDarkness-0.0.5.jar                       | None                                     |
       | LCHIJA | forgelin             | 1.8.4                   | Forgelin-1.8.4.jar                                | None                                     |
       | LCHIJA | fpsreducer           | mc1.12.2-1.20           | FpsReducer-mc1.12.2-1.20.jar                      | None                                     |
       | LCHIJA | futuremc             | 0.2.4.1                 | future-mc-1.12.2-0.2.4.1.jar                      | None                                     |
       | LCHIJA | globalxp             | v1.4                    | globalxp-1.12.x-v1.4.jar                          | None                                     |
       | LCHIJA | gottschcore          | 1.13.1                  | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar    | None                                     |
       | LCHIJA | grapplemod           | 1.12.2-v11.1            | grapplemod-v11.1-1.12.2.jar                       | None                                     |
       | LCHIJA | ichunutil            | 7.2.2                   | iChunUtil-1.12.2-7.2.2.jar                        | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCHIJA | infinity             | 0.13.5                  | Infinity-0.13.5.jar                               | None                                     |
       | LCHIJA | ironbackpacks        | 1.12.2-3.0.8-12         | IronBackpacks-1.12.2-3.0.8-12.jar                 | None                                     |
       | LCHIJA | journeymap           | 1.12.2-5.7.1            | journeymap-1.12.2-5.7.1 (1).jar                   | None                                     |
       | LCHIJA | kjlib                | 1.0.4                   | kjlib-1.0.4.jar                                   | None                                     |
       | LCHIJA | llibrary             | 1.7.9                   | llibrary-1.7.9-1.12.2.jar                         | None                                     |
       | LCHIJA | locks                | 2.5                     | locks-1.12.2-2.5.jar                              | None                                     |
       | LCHIJA | loliasm              | 4.6                     | loliasm-4.6.jar                                   | None                                     |
       | LCHIJA | lootoverhaul         | 1.2                     | LootOverhaul-1.2.jar                              | None                                     |
       | LCHIJA | joypadsplitscreenmod | 1.12.0-0.22             | MCJoypad-Mod-1.12.2.jar                           | None                                     |
       | LCHIJA | minetraps            | 1.0.4                   | MineTraps-1.12.2-(v.1.0.4).jar                    | None                                     |
       | LCHIJA | mowziesmobs          | 1.5.4                   | mowziesmobs-1.5.4.jar                             | None                                     |
       | LCHIJA | multithreadednoise   | 0.0.2                   | MultithreadedNoise-1.12.2-0.0.2.jar               | None                                     |
       | LCHIJA | namepain             | 1.3.1                   | NamePain-1.3.1+Forge-1.12.x.jar                   | None                                     |
       | LCHIJA | nbtedit              | $version                | NBTEdit-0.7.jar                                   | None                                     |
       | LCHIJA | neid                 | 1.5.4.4                 | NotEnoughIDs-1.5.4.4.jar                          | None                                     |
       | LCHIJA | particleculling      | v1.3                    | particleculling-1.12.2-v1.3.1.jar                 | None                                     |
       | LCHIJA | perfectspawn         | 2.1                     | PerfectSpawn-MC1.12.2-2.1.jar                     | None                                     |
       | LCHIJA | pirates              | 0.0.6                   | pirates-0.0.6B.jar                                | None                                     |
       | LCHIJA | playerrevive         | 1.0                     | PlayerRevive_v1.2.40_mc1.12.2.jar                 | None                                     |
       | LCHIJA | portable_lighting    | 1.0.0e                  | portablelighting1.0e.jar                          | None                                     |
       | LCHIJA | randomloot           | 1.7.3                   | randomloot+1.7.4.jar                              | None                                     |
       | LCHIJA | reborncore           | 3.19.5                  | RebornCore-1.12.2-3.19.5-universal.jar            | None                                     |
       | LCHIJA | reccomplex           | 1.4.8.2                 | RecurrentComplex-1.4.8.2.jar                      | None                                     |
       | LCHIJA | simplevoidworld      | 1.2.0.9                 | Simple-Void-World-1.12-1.2.0.9-universal.jar      | None                                     |
       | LCHIJA | skylands             | 1.5.3                   | skylands-1.5.3.jar                                | None                                     |
       | LCHIJA | somanyenchantments   | 0.5.5                   | SoManyEnchantments-0.5.5.jar                      | None                                     |
       | LCHIJA | soundfilters         | 0.11_for_1.12           | SoundFilters-0.11_for_1.12.jar                    | None                                     |
       | LCHIJA | superiorshields      | 1.12.2-1.0.2            | SuperiorShields-1.12.2-1.0.2.jar                  | None                                     |
       | LCHIJA | surge                | 2.0.79                  | Surge-1.12.2-2.0.79.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | switchbow            | 1.5.7                   | switchbow-1.5.7.jar                               | None                                     |
       | LCHIJA | treasure2            | 1.12.0                  | Treasure2-mc1.12.2-f14.23.5.2768-v1.12.0.jar      | None                                     |
       | LCHIJA | uteamcore            | 2.2.5.147               | u_team_core-1.12.2-2.2.5.147.jar                  | None                                     |
       | LCHIJA | unloader             | 1.2.0                   | unloader-1.2.0.jar                                | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-150              | VanillaFix-1.0.10-150.jar                         | None                                     |
       | LCHIJA | vs_world             | 1.12.2-1.0.0            | vs-world-1.12.2-1.0.0.jar                         | None                                     |
       | LCHIJA | vs_control           | 1.12.2-1.1.1            | vs-control-1.12.2-1.1.1.jar                       | None                                     |
       | LCHIJA | walljump             | 1.3.2                   | walljump-1.12.2-1.3.2.jar                         | None                                     |
       | LCHIJA | worldedit            | 6.1.10-SNAPSHOT         | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
       | LCHIJA | zeherlib             | 7.2.05                  | zeherlib-1.12.2-7.2.05-universal.jar              | None                                     |
       | LCHIJA | zombieawareness      | 1.12.1-1.11.16          | zombieawareness-1.12.1-1.11.16.jar                | None                                     |
       | LCHIJA | orelib               | 3.5.2.2                 | OreLib-1.12.2-3.5.2.2.jar                         | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround            | 3.5.4.3                 | DynamicSurroundings-1.12.2-3.5.4.3 6.32.00 PM.jar | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.7            | phosphor-forge-mc1.12.2-0.2.7-universal.jar       | None                                     |
       | LCHIJA | thebetweenlands      | 3.4.9                   | TheBetweenlands-3.4.9-universal.jar               | 38067d6878811efb38b6a045521cfd80b9b60b38 |
       | LCHIJA | additions            | 0.5.2                   | Additions-0.5.2.jar                               | None                                     |
       | LCHIJA | mysticallib          | 1.12.2-1.7.0            | mysticallib-1.12.2-1.7.0.jar                      | None                                     |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.5-168.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.9-core.jar)
                                        thebetweenlands.core.TheBetweenlandsClassTransformer
                                      SoManyEnchantments ASM (SoManyEnchantments-0.5.5.jar)
                                        com.Shultrea.Rin.Transformer.SMEASM
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ParticleCullingLoadingPlugin (particleculling-1.12.2-v1.3.1.jar)
                                        
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      MixinLoaderForge ([[[[[[[[[valkyrien-skies-1.1.7-all]].jar)
                                        
                                      SCFMLCorePlugin (StalkerCreepers-1.12.1.jar)
                                        atomicstryker.stalkercreepers.common.SCTransformer
                                      llibrary (llibrary-1.7.9-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
                                        
                                      EntityCullingPlugin (EntityCulling-1.12.2-5.2.0.jar)
                                        meldexun.entityculling.asm.EntityCullingClassTransformer
                                      ApotheosisCore (Apotheosis-1.12.2-1.12.5.jar)
                                        shadows.ApotheosisTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79.jar)
                                        
                                      Plugin (NotEnoughIDs-1.5.4.4.jar)
                                        ru.fewizz.neid.asm.Transformer
                                      LoadingPlugin (PerfectSpawn-MC1.12.2-2.1.jar)
                                        lumien.perfectspawn.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      MixinBooter ([mixinbooter]-4.1.jar)
                                        
                                      BringMeTheRings plugin (BringMeTheRings-0.4.jar)
                                        zabi.minecraft.bmtr.core.BaublesTransformer
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      LoliASM (loliasm-4.6.jar)
                                        
                                      DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.3.jar)
                                        org.orecruncher.dsurround.asm.Transformer
                                      FutureMC (future-mc-1.12.2-0.2.4.1.jar)
                                        thedarkcolour.futuremc.asm.CoreTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.19.5
              Runtime Debofucsation 1
              Invalid fingerprint detected for RebornCore!
              RenderEngine: 1
  Suspected Mods: Valkyrien Skies Core (valkyrienskies), Entity Culling (entityculling)

Maybe I did something wrong. Just let me know! Hope this helps.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.2.1
