### ISSUE TITLE
Crash with Hbm's Nuclear Tech Mod Reloaded

### ISSUE THREAD

**Issue by Zephyriumtdw** [Meldexun/EntityCulling#59]
**Describe the bug**
Game crashes when unloading Large Launch Pad and another several situations(No reprodice for them, were find while playing).

**To Reproduce**
1. Place Large Launch Pad [hbm:launch_table]
2. Fly far enough to unload 
3. See error

**Versions**
Entity Culling: 5.2.2
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
Hbm's Nuclear Tech Mod Reloaded [hbm-1.6.4a-Gv2.jar](https://www.curseforge.com/minecraft/mc-mods/hbms-nuclear-tech-mod-reloaded/files/3599554)

**Log File**
https://gist.github.com/Zephyriumtdw/dd5ba0964b1df12259411b36d4e5a46a 
Crashes without reproduce was on another pack, but how said VanillaFix reason in HBM and Entity Culling

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.2.3
