### ISSUE TITLE
Mod not working with OptiFine 1.12.2_HD_U_G5_pre1

### ISSUE THREAD

**Issue by reddvilzz** [Meldexun/EntityCulling#6]
**Describe the bug**
The mod is not working, using ingameinfo mod entities are rendered with G5 even when standing from far away.
Tried removing optifine and test, the mod works. 

At first I thought it was because the new optifine have the name preview_OptiFine 1.12.2_HD_U_G5_pre1. So I deleted the preview and test it. Still the culling will not work.

**Versions**
Entity Culling: 2.0.5
Forge: 14.23.5.2855
Minecraft: 1.12.2

**Comment by Meldexun** [comment]
Optifine preview versions are not supported.
