### ISSUE TITLE
[1.12.2] Chests drop fps

### ISSUE THREAD

**Issue by yousoenvious** [Meldexun/EntityCulling#60]
When I put several chests on top of each other, the fps drops from 60 (vsync) to 30. What is interesting is the stable 30 fps as vsync 1/2. Without vsync, it also drops, but not so much. This does not happen with chests from iron chests.
To reproduce just put chests on chests.

Video: https://youtu.be/8DmLLIp23yE (look at fps meter in the upper right corner)

EntityCulling-1.12.2-5.2.3
Forge 14.23.5.2860
Minecraft 1.12.2

**Comment by Meldexun** [comment]
That just means that rendering vanilla chests is slowing down your PC enough to not being able to render 60 FPS. Thus it reduces the target refresh rate to one half of your monitor refresh rate. So this is just how vsync works.

**Comment by yousoenvious** [comment]
Upd: Without vsync, it also divides fps by 2. From 90 to 45. 
There is no such problem without Entity culling. And this is only with vanilla chests if you get close to them, if you move away a little, everything is OK.

**Comment by Meldexun** [comment]
What hardware are you using? And what is your cpu and gpu usage with and without EntityCulling?

**Comment by yousoenvious** [comment]
amd a10 5800k 4.2ghz with integrated graphics 
[video with msi afterburner](https://youtu.be/7Ifo7SEUv_8)
p.s idk what is gpu2

**Comment by Meldexun** [comment]
In that case you might want to disable `openglBasedCulling`.

**Comment by yousoenvious** [comment]
After I turned off openglBasedCulling the game freezes when loading the world. In general, I understand this is due to the fact that I play without a graphics card, right? I just won't use vanilla chests while my graphics card is being repaired.
If this problem is only with me, you can close the topic. Don't you have an fps drop?
