### ISSUE TITLE
Incompatibility with Optifine HD U G5 and Valkyrien skies? [1.12.2]

### ISSUE THREAD

**Issue by genutk** [Meldexun/EntityCulling#61]
**Describe the bug**
Having only Valkyrien Skies, OptiFine HD U G5 and EntityCulling loaded in it would crash on ship assembly

**To Reproduce**
1.Build a ship like normal
2.Upon assembling ship with Optifine it causes a crash
3.Turning off openglBasedCulling doesn't crash but makes tile entities on ship invisible

**Screenshots/Videos**
https://youtu.be/6EpjI9VKyzQ

**Versions**
EntityCulling-1.12.2-5.2.2
Forge : 1.12.2-forge-14.23.5.2860
Minecraft:  1.12.2
Other mods (necessary to reproduce the bug): 
OptiFine_1.12.2_HD_U_G5
valkyrien-skies-1.1.7-all
vs-control-1.12.2-1.1.1
vs-world-1.12.2-1.0.0

**Log File**
https://gist.github.com/genutk/990d2f56646488f439b1d38ac08b6a35

**Comment by Meldexun** [comment]
Fixed in v1.12.2-5.3.1
