### ISSUE TITLE
Entities disappear at a certain angle when aiming with a sight(Incompatility with ModularWarfare)

### ISSUE THREAD

**Issue by Zephyriumtdw** [Meldexun/EntityCulling#62]
**Describe the bug**
When aiming with a weapon from ModularWarfare using a scope, entities that do not fall into the scope disappear. I tried to change everything in the config, but nothing except enabled=false helped

**To Reproduce**
1. Take any gun and attach any scope(I've used Mosin Nagant and Obzor Sight)
2. Spawn something
3. Press RMB
4. Look in different directions watching the summoned creature

**Screenshots/Videos**
[enabled=true](https://imgur.com/XVcMFPW)
[enabled=true/no mod](https://imgur.com/ZwZN7ce)

**Versions**
Entity Culling: 5.3.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
[modularwarfare-1.1.1f.jar](https://www.curseforge.com/minecraft/mc-mods/modularwarfare)

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-6.1.0
