### ISSUE TITLE
[1.12.2] Flan's mod

### ISSUE THREAD

**Issue by Dan4oby** [Meldexun/EntityCulling#64]
**Describe the bug**
Flan's mod vehicles dont cull at all.

**Screenshots/Videos**
Three screenshot with descriptions:
https://imgur.com/a/M62aW8b

**Versions**
Entity Culling: last
Forge: last
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug):

**Comment by Meldexun** [comment]
Please test if this is also happening without EntityCulling installed.

**Comment by Dan4oby** [comment]
> Please test if this is also happening without EntityCulling installed.

Same thing happens. Bad fps drops.

**Comment by Meldexun** [comment]
Then this is not an EntityCulling issue. Report it to the autor(-s) of Flan's Mod.
