### ISSUE TITLE
[1.12.2] Crash with Blood Magic Mimic Block

### ISSUE THREAD

**Issue by Serega007RU** [Meldexun/EntityCulling#65]
**Describe the bug**
Crash with the Blood Magic mod due to the Mimic Block

**To Reproduce**
1. Enter the world (for example, in a single game)
2. Place Ethereal Opaque Mimic Block in the world
3. Tadam, your game will crash

**Screenshots/Videos**
![image](https://user-images.githubusercontent.com/64780091/166156702-9a0872f3-6b53-4efe-8bd6-fdf1a2eea584.png)

**Versions**
All this information is in the crash report, but I will duplicate this here if necessary
Entity Culling: 5.3.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): \
Blood Magic: 2.4.3-105

**Log File**
[latest.log](https://github.com/Meldexun/EntityCulling/files/8599386/latest.log)

**Crash Report**
[crash-2022-05-01_20.19.40-client.txt](https://github.com/Meldexun/EntityCulling/files/8599387/crash-2022-05-01_20.19.40-client.txt)

Without EntityCulling, the game does not crash and everything works fine

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-5.3.2
