### ISSUE TITLE
[1.12.2] Everything crash

### ISSUE THREAD

**Issue by Serega007RU** [Meldexun/EntityCulling#66]
**Describe the bug**
Everything crash

**To Reproduce**
1. Just enter the world

**Screenshots/Videos**
No need

**Versions**
Entity Culling: 5.3.2
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 

**Log File**
[latest.log](https://github.com/Meldexun/EntityCulling/files/8599772/latest.log)

**Crash report**
[crash-2022-05-02_00.25.16-client.txt](https://github.com/Meldexun/EntityCulling/files/8599773/crash-2022-05-02_00.25.16-client.txt)

There are no such problems on version 5.3.1

Here are more crash reports from my players (with an modpack of 100+ mods), I understand these crashes are also involved in this problem, since it does not crash on version 5.3.1
[crash-2022-05-02_00.21.16-client.txt](https://github.com/Meldexun/EntityCulling/files/8599786/crash-2022-05-02_00.21.16-client.txt)
[crash-2022-05-02_00.19.36-client.txt](https://github.com/Meldexun/EntityCulling/files/8599787/crash-2022-05-02_00.19.36-client.txt)

**Comment by Meldexun** [comment]
The uploaded file was somehow corrupted. Redownloading the should fix this.
