### ISSUE TITLE
crash with computronics

### ISSUE THREAD

**Issue by xemnes** [Meldexun/EntityCulling#67]
hello
i stumbled across a crash today when i loaded my world
the crash report claims to be because of this mod and computronics
heres the crash report https://pastebin.com/v3M6Syqh

**Comment by Meldexun** [comment]
Use the issue template and update the mod.

**Comment by xemnes** [comment]
oh sorry, i wasnt aware this was fixed in later versions. the crash was random, first time i have experienced it so its hard to replicate, i also did a search for it and i couldnt find anything.
