### ISSUE TITLE
ver 6.0.2 failed to start

### ISSUE THREAD

**Issue by rebarakuk** [Meldexun/EntityCulling#69]
**Describe the bug**
Minecraft failed to start. And according to latest log, renderlib@[1.0.6,) is not involved in entityculling maybe??
Also, with 5.3.3, this crash doesn't happen

**Versions**
Entity Culling: 6.0.2
Forge: 14.23.5.2860
Minecraft: 1.12.2

**Log File**
[crash report](https://gist.github.com/rebarakuk/1821551fb9503a7adf0560f32aaa2ce3)

[latest log](https://gist.github.com/rebarakuk/b903582f9f74f5f7138544c0634f6c99)

**Comment by Meldexun** [comment]
EntityCulling 6.0.0 and newer requires RenderLib to be installed.
