### ISSUE TITLE
Incompatibility with Cubic Chunk

### ISSUE THREAD

**Issue by border999** [Meldexun/EntityCulling#7]
**Describe the bug**
When attempting to play on a world the game will immediately crash once the world is loaded.

**To Reproduce**
Install Cubic Chunks
Open a world with the 'Vanilla generation' with 'Cubic Chunks world type enabled'
Crash when the world opens up.

**Expected behavior**
Normal gameplay.

**Versions**
Entity Culling: 1.12.2-2.0.5
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2
CubicChunks-1.12.2-0.0.1182.0-SNAPSHOT-all

**Other**
Crash report (upload as a file): 
[crash-2021-01-21_13.59.43-client.txt](https://github.com/Meldexun/EntityCulling/files/5852906/crash-2021-01-21_13.59.43-client.txt)
Latest log (upload as a file): 
[logs.zip](https://github.com/Meldexun/EntityCulling/files/5852886/logs.zip)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Cubic Chunks

**Comment by Meldexun** [comment]
Not reproduceable with only entity culling and better portals. Can only be worked on when the the incompatible mod is known.

**Comment by border999** [comment]
Try cubic chunks, it also alters how the world is structured.

**Comment by border999** [comment]
using MixinCompat-0.8 to get Better Portals and Cubic chunks to behave. Also renamed Better Portals to "TheBetterPortals" to make sure it loaded after Cubic Chunks.

**Comment by Meldexun** [comment]
No, you should test which mod is causing the problem and then come back and tell me that entity culling together with mod X is crashing the game or something. I won't test all mods of your modpack until I found the one that's causing problems.

**Comment by border999** [comment]
[crash-2021-01-18_16.25.42-client.txt](https://github.com/Meldexun/EntityCulling/files/5833244/crash-2021-01-18_16.25.42-client.txt)
try making a world using the hybrid world option

**Comment by border999** [comment]
i've whittled it down to seven mods. Hybrid world messes with world gen in between y:0 and +256

**Comment by border999** [comment]
[crash-2021-01-18_16.31.45-client.txt](https://github.com/Meldexun/EntityCulling/files/5833269/crash-2021-01-18_16.31.45-client.txt)
six mods, removed mixin compat

**Comment by border999** [comment]
in case you're wondering where to find hybridworld
http://www.mediafire.com/file/sttykphqeklusiy/hybridworld-1.12.2-0.2.2.jar/file

**Comment by border999** [comment]
in case you are waiting for me to put the mod names here instead of looking at the crash report.
CubicChunks-1.12.2-0.0.1182.0-SNAPSHOT-all
CubicWorldGen-1.12.2-0.0.140.0-SNAPSHOT-all
EntityCulling-1.12.2-2.0.5
Forgelin-1.8.4
hybridworld-0.2.2
TheBetterPortals-0.3.7.7 (Renamed from Better Portals)

**Comment by border999** [comment]
is this sufficient information?

**Comment by border999** [comment]
are you investigating?

**Comment by sirati97** [comment]
Is this happening if you do not use Hybridworld and instead create a CubicChunks world?

**Comment by border999** [comment]
[crash-2021-01-21_13.59.43-client.txt](https://github.com/Meldexun/EntityCulling/files/5852766/crash-2021-01-21_13.59.43-client.txt)
Default generation option for Cubic Chunks with Hybrid worlds removed causes the same crash.

**Comment by sirati97** [comment]
Thats what I thought. Hybrid world does not change anything in regard to what this mods changes. 

Dont forget to update the title of this issue as well. Also just checking, is what you tried using the Cubic Chunks World Generator or did you use Vanilla world generator with Cubic Chunks turned on?

 If the latter is the case you can reduce the mod list to:
- CubicChunks-1.12.2-0.0.1182.0-SNAPSHOT-all
- EntityCulling-1.12.2-2.0.5
- Forgelin-1.8.4
- TheBetterPortals-0.3.7.7

**Comment by border999** [comment]
Vanilla Generator with Cubic Chunks turned on.

**Comment by sirati97** [comment]
Now last question: it only happens when you have Better Portals and CC right

**Comment by border999** [comment]
[crash-2021-01-21_14.24.41-client.txt](https://github.com/Meldexun/EntityCulling/files/5852832/crash-2021-01-21_14.24.41-client.txt)
slightly different crash

**Comment by border999** [comment]
seems so odd then that Better Portals kept popping up in the crash log

**Comment by sirati97** [comment]
there we go. now you did all the work letting the developer know what causes the problem. 😉

no thats not odd at all better portals loads multiple words at the same time, so it replaces vanillas world renderer with one that can handle multiple worlds

**Comment by border999** [comment]
done

**Comment by sirati97** [comment]
Cubic Chunks generation option enabled
should be
Cubic Chunks world type enabled.

**Comment by border999** [comment]
Cubic Chunks adds an extra button to select if you want cubic chunks turned on. CubicWorldGen enables you to customize the generation.
![Screenshot (304)](https://user-images.githubusercontent.com/11824584/105430348-5e2d2a00-5bf7-11eb-98cc-0d51464100d3.png)

**Comment by sirati97** [comment]
The button you see there: 'CubicChunks: Default' enables cubic chunk worlds, you do not need CubicWorldGen for that. 

If you keep it like this, it is 'Vanilla generation' with 'Cubic Chunks world type enabled'

**Comment by border999** [comment]
done

**Comment by border999** [comment]
so what are you thinking is the issue? Something with how Cubic Chunks changes the chunk formating or something like that?

**Comment by Meldexun** [comment]
Fixed in v2.0.6
