### ISSUE TITLE
The disappearance of the entity and blocks at a certain angle

### ISSUE THREAD

**Issue by MineCinema** [Meldexun/EntityCulling#70]
**Describe the bug**
With the new versions, I began to observe such disappearance of entities or blocks.

**Screenshots/Videos**
https://gifyu.com/image/SH41a

**Versions**
Entity Culling: 1.12.2-6.0.2
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods 
RenderLib-1.12.2-1.0.8

Maybe there is some parameter in confing that should be tweaked because I didn't notice it on version 1.12.2-4.2.5

**Comment by Meldexun** [comment]
It is working fine for me. Please provide a reliable way to reproduce this with as few other mods as possible installed.

**Comment by Meldexun** [comment]
Are you able to reproduce this with EntityCulling-1.12.2-6.1.0?

**Comment by MineCinema** [comment]
> Вы можете воспроизвести это с помощью EntityCulling-1.12.2-6.1.0?

Постараюсь завтра проверить.

**Comment by MineCinema** [comment]
> Можете ли вы воспроизвести это с помощью EntityCulling-1.12.2-6.1.0?

Good day. I checked the disappearance of objects on the version EntityCulling-1.12.2-6.1.0.
I could not thoroughly check everything, there is no time. But at first glance, the objects no longer disappear.
Later I will check in more detail and if there are problems I will report.

**Comment by Meldexun** [comment]
Fixed in v1.12.2-6.2.0
