### ISSUE TITLE
Game crashes even with only the mod + Optifine installed

### ISSUE THREAD

**Issue by CorruptedPlazma** [Meldexun/EntityCulling#72]
**Describe the bug**
The mod causes the game to not load at all, neither with or without other mods.

**To Reproduce**
1. Install mod
2. Attempt to launch

**Screenshots/Videos**
N/A

**Versions**
Entity Culling: 1.12.2-6.1.0
Forge: 14.23.5.2859
Minecraft: 1.12.2
Other mods: None, besides Optifine G5

**Log File**
https://gist.github.com/CorruptedPlazma/67e60ebd2dee0438178f05a81a8a139e

**Comment by quentin452** [comment]
Do you have renderlib , mixincompat07-08 , MixinBootstrap mod installed?

**Comment by CorruptedPlazma** [comment]
I do not, I assume they are dependencies? I didn't notice any mention of them on the CurseForge page

**Comment by CorruptedPlazma** [comment]
I cannot read, mod works perfectly now. Closing.
