### ISSUE TITLE
[1.12.2] IndexOutOfBoundsException when accessing visibility buffer

### ISSUE THREAD

**Issue by 623667595** [Meldexun/EntityCulling#74]
**Describe the bug**
Teleport to Main city game black screen, other worlds are not tested.

**To Reproduce**
Teleport to Main city game black screen, other worlds are not tested.

Screenshots/Videos

The game directly black screen does not respond, has been replaced to the old version.

Versions
Entity Culling: 6.2.0-6.2.1
Forge: 14.23.5.2860
Minecraft: 1.12.2

Nothirium-1.12.2-0.1.8-beta
RenderLib-1.12.2-1.1.2
EntityCulling-1.12.2-6.2.0~6.2.1
Other mods (necessary to reproduce the bug):

Log File
The game did not crash, instantaneous black screen did not respond.

**Comment by Meldexun** [comment]
Is Nothirium required to reproduce the issue?

Also please provide a log file.

**Comment by 623667595** [comment]
I will try to delete Nothirium and submit the report later.

**Comment by 623667595** [comment]
> 是否需要 Nothirium 才能重现该问题？
> 
> 另请提供日志文件。
![image](https://user-images.githubusercontent.com/88877796/183251906-30bad766-f581-4d87-8cb8-260fb5ea8412.png)
Delete or there is a problem, is EntityCulling after the update of the problem.

**Comment by 623667595** [comment]
[crash-2022-08-06_21.53.58-client.txt](https://github.com/Meldexun/EntityCulling/files/9275157/crash-2022-08-06_21.53.58-client.txt)

**Comment by Meldexun** [comment]
Please update RenderLib to v1.12.2-1.1.3 and set the `enableGLDebug` config option from RenderLib to true. Then try to reproduce the issue and upload the log file (for example https://gist.github.com/).

**Comment by 623667595** [comment]
> 请将 RenderLib 更新到 v1.12.2-1.1.3 并将 RenderLib 的`enableGLDebug`配置选项设置为 true。然后尝试重现问题并上传日志文件（例如https://gist.github.com/）。

![image](https://user-images.githubusercontent.com/88877796/183565894-d7d7772e-1404-4f78-8b0e-a7100e36977b.png)
[crash-2022-08-09_12.39.04-client.txt](https://github.com/Meldexun/EntityCulling/files/9286792/crash-2022-08-09_12.39.04-client.txt)

**Comment by 623667595** [comment]
![image](https://user-images.githubusercontent.com/88877796/183565946-9ee70b5a-bb15-41fb-a900-7921d70795b8.png)
useless

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-6.2.2
