### ISSUE TITLE
[1.12.2] Incompatible with Hats mod

### ISSUE THREAD

**Issue by mjra007** [Meldexun/EntityCulling#79]
**Describe the bug**
Hats from hats mod seem to disappear and reappear randomly. As far as I could see these hats are entities but they are not registered and therefore they do not have a registered entity name that can be added to the list of entities that will always be rendered in the entity culling config. 

[You can see a video here of it happening](https://i.imgur.com/mEvTkpa.mp4)

**Reproducibility** 
- [X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Put yourself in creative
2. Click on key "H" the hats gui will pop up.
3. Select any hat from the list and click done.
4. Move around a bit.

**Screenshots/Videos**
 https://i.imgur.com/oaDL8Ry.mp4
**Versions**
Entity Culling:  EntityCulling-1.12.2-6.2.2
Forge: 14.23.5.2860
Minecraft: 1.12.2
RenderLib: RenderLib-1.12.2-1.1.4
Other mods (necessary to reproduce the bug): 
Hats: 1.12.2-7.1.1
iChunUtil: 1.12.2-7.2.2
_MixinBootstrap-1.1.0

**Hardware**
CPU: AMD Ryzen 5 1600x
RAM: 16GB
GPU: nvidia gtx 1080
VRAM: 8GB

**Log File**
https://gist.github.com/mjra007/37d5ac2a9da6d8e230bcd71088486fc8

**Comment by Meldexun** [comment]
Fixed in v1.12.2-6.2.3
