### ISSUE TITLE
Incompatibility with Cubic Chunks using vanilla world

### ISSUE THREAD

**Issue by border999** [Meldexun/EntityCulling#8]
**Describe the bug**
I attempted to generate a vanilla world with the cubic chunks world generation option set to no and it crashed during generation.

**To Reproduce**
1. Use both Cubic Chunks and Entity Culling.
2. Attempt to generate a world with the generation option on the CC button set to "no"
3. Crash

**Expected behavior**
I wanted to test if a separate issue would occur on a vanilla world when Entity Culling and CC were installed, instead I found another bug to report.

**Versions**
Entity Culling: EntityCulling-1.12.2-2.0.6
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2

**Other**
Crash report (upload as a file): 
[crash-2021-01-23_13.20.14-client.txt](https://github.com/Meldexun/EntityCulling/files/5861304/crash-2021-01-23_13.20.14-client.txt)
Latest log (upload as a file): 
[logs.zip](https://github.com/Meldexun/EntityCulling/files/5861307/logs.zip)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Cubic Chunks
Other mods (that are also installed): Cubic Chunks

**Comment by Meldexun** [comment]
Fixed in v2.0.7
