### ISSUE TITLE
[1.12.2] Invisible Pokecube Mobs

### ISSUE THREAD

**Issue by Airisii** [Meldexun/EntityCulling#81]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Install Pokecube with Entity Culling
2. Open World
3. Look for Pokecube mobs
4. See they are invisible 

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem. If you are reporting invisible entities or tile entities then please enable the `debugRenderBoxes` config option when making screenshots/videos!
![2023-04-19_09 27 50](https://user-images.githubusercontent.com/34899528/233089780-df77c4d1-c29a-4032-8e82-287434bf3030.png)

**Versions**
Entity Culling: 6.3.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
Pokecube: 1.18.2
MixinBootstrap: 1.1.0
Renderlib: 1.2.8

**Hardware**
CPU: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
RAM: 16gb
GPU: Intel(R) UHD Graphics
VRAM: 128 (?)

**Log File**
Providing a log file is always necessary no matter if the game crashed or not. This also means that the crash report is not needed.
Please use a paste site to upload the log file (for example https://gist.github.com/) and provide the link to the file here.

https://pastebin.com/QHRySyKr

**Comment by Meldexun** [comment]
Fixed in RenderLib-1.12.2-1.3.1
