### ISSUE TITLE
[1.12.2] Beacon beams aren't visible

### ISSUE THREAD

**Issue by xJon** [Meldexun/EntityCulling#82]
Using the latest version of Entity Culling (`6.3.1`) and RenderLib (`1.2.8`), installed on their own (with Forge `14.23.5.2860`).
Disabling Entity Culling resolves the issue.
To reproduce setup a beacon, you will see the beam render for a moment and then it will disappear.

**Screenshots/Videos**
![image](https://github.com/Meldexun/EntityCulling/assets/8945347/6e496bf4-efe6-4b7d-93a6-8a72fbac0cbc)

**Hardware**
N/A (reproducible by other players with different systems).

**Log File**
https://mclo.gs/RuM1ocD

**Comment by Meldexun** [comment]
Fixed in RenderLib-1.12.2-1.3.1
