### ISSUE TITLE
when moving around sometimes entities disappear for a sec when openglbasedculling is on

### ISSUE THREAD

**Issue by Floi1** [Meldexun/EntityCulling#83]
**Describe the bug**
when moving around sometimes entity disappears for a sec when openglbasedculling is on when moving

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Go to 'go in game and turn on openglbasedculling '
2. Click on 'then you will see entities disappear for a sec when moving around'

**Screenshots/Videos**

https://github.com/Meldexun/EntityCulling/assets/91851019/2ad35af0-8c1c-4356-aa8b-c49dcffa33a1

https://github.com/Meldexun/EntityCulling/assets/91851019/3e8b5505-0551-4b28-b1cd-be3e5cf4898f

**Versions**
Entity Culling: 6.4.1
RenderLib: 1.3.1
Forge: 1.12.2 - 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): 
MixinBootstrap

Hardware
CPU: AMD amd ryzen 5 5500U
RAM: 8GB
GPU: Igpu vega 7
VRAM: idk

**Log File**

**Comment by Floi1** [comment]
i just updated my amd driver to 23.7.2 it seems to fix the issue for me so this is a amd driver issue. In the old video i was using amd driver 23.7.1

https://github.com/Meldexun/EntityCulling/assets/91851019/69fbd263-287a-4e2f-bdd9-9b2e37e4a696

**Comment by Meldexun** [comment]
I will close this then.
