### ISSUE TITLE
[1.12] Vampirism Blood Vision Breaks

### ISSUE THREAD

**Issue by Hydraheads** [Meldexun/EntityCulling#84]
**Describe the bug**

If you buy the blood vision skill on the vampire skill tree of the vampirism mod (1.12), it fails when mobs are being culled. Blood vision is supposed to see living mobs behind walls by applying a red glowing type effect. In theory, if the mod disabled itself while blood vision was active this would be fixed, would love to have this mod in my pack it's so good for fps

**Reproducibility**
- [ X] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. Get Blood vision
2. Turn it on
3. Look at an entity covered inside of a wall…

**Versions**
Entity Culling: 6.4.1
Forge: Latest
Minecraft: 1.12
Other mods (necessary to reproduce the bug): Vampirism

**Comment by Meldexun** [comment]
Fixed in RenderLib-1.12.2-1.3.4
