### ISSUE TITLE
The end crystal beam is not visible

### ISSUE THREAD

**Issue by Serega007RU** [Meldexun/EntityCulling#85]
**Describe the bug**
When the dragon is reborn, the end crystal beam is not visible if the end crystal does not fall into the frame (on the screen), see the video for more details

**Reproducibility**
- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

**To Reproduce**
1. start the dragon rebirth
2. make sure that the crystal of the end does not fall into the frame (on the screen)
The End crystal beam becomes invisible

**Screenshots/Videos**
https://www.youtube.com/watch?v=JgnfQHyUKjE

**Versions**
Entity Culling: 6.4.1
Forge: 14.23.5.2860
Minecraft: 1.12.2
Other mods (necessary to reproduce the bug): not required

**Hardware**
CPU: Intel Xeon E5-2666 v3
RAM: 48 GB
GPU: Intel Arc A380
VRAM: 6 GB

**Log File**
[2023-07-31-5.log.gz](https://github.com/Meldexun/EntityCulling/files/12221599/2023-07-31-5.log.gz)

**Comment by Meldexun** [comment]
Fixed in v1.12.2-6.4.3
