### ISSUE TITLE
1.19.2 Client Crash 

### ISSUE THREAD

**Issue by mxnmnm** [Meldexun/EntityCulling#86]
Disclaimer: If applicable please set the `openGLDebugOutput -> enabled` config option from RenderLib to true and try to reproduce the issue.

**Describe the bug**
My client crashes randomly when exploring the nether. I can log back in and the server does not crash.
I made some other issues with other mods that the crash report thought were responsible. 
https://github.com/embeddedt/embeddium/issues/142
https://github.com/Jozufozu/Flywheel/issues/216

**Reproducibility**
Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results. To check a checkbox replace the space between the square brackets with an x (like this [x]) or create the issue and check the checkbox by clicking on it.
- [ ] I reproduced this issue with as few other mods as possible installed.
- [x] I am unable to reproduce this issue consistently.

**To Reproduce**
Steps to reproduce the behavior.
Please keep in mind that I most likely don't know how other mods involved in this issue work. Thus terms like "Go to dimension X" should be explained in more detail because I probably don't know how to do that.
1. Explore the nether in a brand new world
2. Randomly crash 

**Screenshots/Videos**
If applicable, add screenshots or videos to help explain your problem. If you are reporting invisible entities or tile entities then please enable the `debugRenderBoxes` config option when making screenshots/videos!

**Versions**
Entity Culling: 1.6.1
Forge: 43.3.5
Minecraft: 1.19.2
Other mods (necessary to reproduce the bug): These are all of the mods I used idk which ones were problematic vs not: https://gist.github.com/mxnmnm/affa3b56a60c369cd2f56e56b3ecea38

**Hardware**
CPU: 13700k
RAM: 32gb 12 dedicated to the server and 12 to the client
GPU: 1080ti
VRAM: 11gb

**Log File**
https://gist.github.com/mxnmnm/123896114b861eaa19ba80f6f25cda6a

**Comment by quentin452** [comment]
@mxnmnm you made an issue report in the wrong repo , here is the good repo https://github.com/tr7zw/EntityCulling/issues

**Comment by mxnmnm** [comment]
omg im sorry i was super tired
