### ISSUE TITLE
[1.12.2] Project-Red Lighting Visual Effect Doesn't Work Correctly

### ISSUE THREAD

**Issue by Bawhoppen** [Meldexun/EntityCulling#88]
The fancy lighting visual glow effects for Project-Red lighting blocks do not work correctly with Entity Culling installed, even when looking directly at them without them being obstructed. The full-block one still works correctly, so I assume this has something to do with Multipart? 

How they should look with visual effect: 
![2024-03-26_00 09 01](https://github.com/Meldexun/EntityCulling/assets/6510293/d02ac90c-ef8a-4a73-9d82-46dd0af01619)
After adding Entity Culling + Render Lib:
![2024-03-26_00 28 11](https://github.com/Meldexun/EntityCulling/assets/6510293/920f58d4-d5fe-40a9-85f3-58497f76cae4)

 Mods:
ProjectRed-1.12.2 -4.9.4.120 [all of the several sub-mods it is split into, these blocks come from ProjectRed-Lighting specifically]
CodeChickenLib-1.12.2-3.2.3.358-universal [required for ProjectRed]
MrTJPCore-1.12.2-2.1.4.43 [required for ProjectRed]
ForgeMultipart-1.12.2-2.6.2.83-universal  [required for ProjectRed]
MixinBootstrap-1.1.0
EntityCulling-1.12-6.4.3
RenderLib-1.12.2-1.3.4

Forge Version: 14.23.5.2854

**Comment by xJon** [comment]
Would be really appreciated to have this resolved.

**Comment by xJon** [comment]
Can confirm it does not occur with version `3.0.1`, but does with `4.0.0`.

**Comment by Meldexun** [comment]
Fixed in RenderLib-1.12.2-1.3.5

**Comment by Bawhoppen** [comment]
Hey cool, thanks!
