### ISSUE TITLE
Broken visual rendering on Cubic Chunks worlds.

### ISSUE THREAD

**Issue by border999** [Meldexun/EntityCulling#9]
**Describe the bug**
I can't see mobs of any kind in the world. I have various other mods that enabled me to notice that they were in fact there, but I immediately stripped the mod list back down to Cubic Chunks and Entity Culling and the issue persisted. Went creative and tried spawning a bunch of zombies. All invisible including when attempting to display their hitboxes but otherwise completely normal.
**To Reproduce**
1. Using both Cubic Chunks and Entity Culling generate a world with the Cubic Chunks generation option set to default.
2. If you wish, use commands or creative mod to force spawn a mod and see that it doesn't visually appear.

**Expected behavior**
Visible mobs.

**Versions**
Entity Culling: 2.0.6
Forge: 1.12.2-forge-14.23.5.2854
Minecraft: 1.12.2

**Other**
Latest log (upload as a file): [nothing really here.zip](https://github.com/Meldexun/EntityCulling/files/5861338/nothing.really.here.zip)
Singleplayer/Multiplayer: Singleplayer
Other mods (that are necessary to produce the bug): Cubic Chunks
Other mods (that are also installed): Cubic Chunks

**Comment by Meldexun** [comment]
Fixed in v2.0.7
